### ISSUE TITLE
[FEATURE]: Add About Section in the page

### ISSUE THREAD

**Issue by ShaileshKumar007** [WebXDAO/WebXDAO.github.io#103]
### Detailed description

There should be an About Section on the website's landing page. And when the user clicks on the "About Us" in the navbar it should send the user to that "About Section".

### Context

The “About Us” section can effectively communicate your team's values and how they may align with a potential customer's goals.

### Possible implementation

We can add an about section on the page and the following can be the content for the "About Section" :
![web3comm](https://user-images.githubusercontent.com/71178959/137402835-790df9fd-07bb-4c3b-8a29-b275668bb516.JPG)

### Additional information

While clicking on the "About Us" in the navbar it should take us to the About Section of the page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KendallDoesCoding** [comment]
> @japneetsingh035 Currently the issue is on-hold and we are waiting for the redesign :) Thanks for showing interest in contributing, we do have other repos that you can check out

> I will like to work on this issue.

When the issue isn't on hold anymore 😄

**Comment by KendallDoesCoding** [comment]
As this issue is on hold maybe, don't show the "About" section on the website for now, until this get's done as it leads no where. I can try to remove it from the site, if yall are down with the idea.

![image](https://user-images.githubusercontent.com/84712013/154264625-6df8dcfb-b350-440c-a881-b30deb4ed53a.png)

**Comment by krshkodes** [comment]
Close in favour of #198

**Comment by KendallDoesCoding** [comment]
hi
