### ISSUE TITLE
[FEATURE] Add information about our moderators

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#107]
### Detailed description

Now that we have a page for our moderators (thanks to @shreyaansjain06), feel free to add a bio of yourself to appear on the page!

### Context

Currently, we just have random texts set on that page. Other people can know more about us on that page.

### Possible implementation

Add short information about yourself. **Please comment here and we'll make a PR to add it.** 🙂

### Additional information

Nope.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Okay, to start, this is mine 😄 

> Open-source maintainer/contributor 💻 Bot/website maintainer for [@Heptagram](https://heptagram.xyz) 🤖 [@Minetest](https://minetest.net) mod/game maintainer & creator 🎮 Discord moderator in 20+ servers 🛡 Open-source/DSA mentor 🛠

**Comment by shuklaritvik06** [comment]
Mine
> Co-Founder | Open Source Enthusiast | Poet | Community 💛

**Comment by Panquesito7** [comment]
Is the 2.0 version still being built? I think we should add them soon; it's been almost 20 days. @krishguptadev.

**Comment by krishguptadev** [comment]
> Is the 2.0 version still being built? I think we should add them soon; it's been almost 20 days. @krishguptadev.
> 

Let's keep the websitev1 still updating, I think this was paused due to the devprtcl site... But yeah I think we can continue this now, we can build V2 in parallel 🙂

**Comment by Panquesito7** [comment]
Hey, @shreyaansjain06! Do you still want to work on this?

**Comment by shreyaansjain06** [comment]
yes please share the new design i will make according to it

**Comment by Panquesito7** [comment]
> yes please share the new design i will make according to it

The page is already there, you just need to add our bio's. 🙂

**Comment by mkubdev** [comment]
> Open-source maintainer/contributor 💻 Bot/website maintainer for [@Heptagram](https://heptagram.xyz) 🤖 [@Minetest](https://minetest.net) mod/game maintainer & creator 🎮 Discord moderator in 20+ servers 🛡 Open-source/DSA mentor 🛠

And mine 😄 
> Web2 Fullstack Software Engineer 💠 I build webapps and mobile apps for the industry field 🔧 Transitioning to Web3 stacks 🌠 Maintainer for [@Web3community](https://web3community.github.io/) 🍬  Open-source newby!

**Comment by Panquesito7** [comment]
@krishguptadev, could you please add yours? Now that you're a moderator. 🙂

**Comment by krishguptadev** [comment]
How about...

Started my tech journey on 30th September 2021. Since then, I am learning new things and growing my network. I love to chat, collaborate and contribute. I am an open sourcer, that's my complete bio.

**Comment by KendallDoesCoding** [comment]
@Panquesito7 This seems to be done, Please close this issue.

**Comment by KendallDoesCoding** [comment]
Thanks!
