### ISSUE TITLE
[FEATURE] Add a branding page in the website

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#116]
### Detailed description

We have a [Brand Assets](https://github.com/web3community/brand-assets) repository, but I think we should also have a page for our brand assets on our website. That way, people can find it easier and quicker.

The first thing one would do (I guess 😅 ) would be to check the website. If they wanna use our logos, they'll find our guidelines quickly. 🙂

### Context

This would help our users find our branding assets/guidelines easier and quicker.

### Possible implementation

Add a branding page to our website.

### Additional information

This can be implemented soon or wait until the v2 is released.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
will be added on v3 soon!
