### ISSUE TITLE
[FEATURE] Update testimonials cards

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#125]
### Detailed description

We should update the testimonials cards.
![Capture](https://user-images.githubusercontent.com/50140834/141095018-9b25bc06-2fdb-421b-b2c6-738e0156e95f.JPG)

### Context

There is mocked content still in the website. But maybe this will be removed in v2 ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orion-esu** [comment]
If there's an available design I'll want to work on it.

**Comment by Panquesito7** [comment]
> If there's an available design I'll want to work on it.

You just need to update the images, names, stars, and titles. All testimonials (new ones and current ones) are in https://github.com/web3community/web3community.github.io/discussions/50.

**Comment by unnikrishnan2002** [comment]
I would like to work on this issue @Panquesito7

**Comment by mkubdev** [comment]
I close, passed by #187
