### ISSUE TITLE
[BUG] Cards not properly stacking on hover Community Partners page

### ISSUE THREAD

**Issue by technophile-04** [WebXDAO/WebXDAO.github.io#145]
### Description of the bug

The cards on the Community Partners page are not properly stacking on each other. The cards which are on the left side are always staying below the cards on the right, on the hover

### Before : 
<img width="1440" alt="Screenshot 2021-12-05 at 1 31 50 PM" src="https://user-images.githubusercontent.com/80153681/144738754-6359fdfb-f20c-4532-b9f9-a5db83da15ef.png">
(in the above image Dev Protocol card is being hovered and the same happens for the Logo 2 cards)

### After : 
<img width="1440" alt="Screenshot 2021-12-05 at 1 34 16 PM" src="https://user-images.githubusercontent.com/80153681/144738841-d0306a7b-3afc-495d-a49c-fc67089178a7.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
Will work on this one, if no one else will.

**Comment by mkubdev** [comment]
> I'm willing work on this one, if no one else will.

Sure!

**Comment by mkubdev** [comment]
I close, #146 solved it.
