### ISSUE TITLE
[BUG] CryptoZombies logo is stretched

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#148]
### Description of the bug

The CryptoZombies logo is stretched. It doesn't look good like that.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/51391473/147592685-069d1b4d-db3d-410b-b77e-64d19d774a65.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unnikrishnan2002** [comment]
Do we have other image assets for CryptoZombies?

**Comment by Panquesito7** [comment]
> Do we have other image assets for CryptoZombies?

Nope, I think we don't. We might have to search for its logo on the web.

**Comment by mkubdev** [comment]
I close, solved by #187
