### ISSUE TITLE
[BUG] The social media icons alignment is altered in certain viewports

### ISSUE THREAD

**Issue by unnikrishnan2002** [WebXDAO/WebXDAO.github.io#149]
### Description of the bug

The social media icons alignment is altered while in chrome desktop site in android. 

Device : Realme Narzo 20
OS : Android 11
Browser : Google Chrome
Mode : Desktop Site

### Please add screenshots (if applicable)

![IMG_20220103_101949](https://user-images.githubusercontent.com/76985777/147902284-e06d8322-26c8-4f02-b76a-299d58fedfce.jpg)

### Add any other context about the problem here

Possible Solution : 
I guess shifting the socials section from left to bottom should fix the issue 

Like this
![image](https://user-images.githubusercontent.com/76985777/147902703-499a6a11-7764-407f-b191-01cc6c9eb515.png)

PS : I didn't check it . I just edited out the above image to convey the meaning
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anosh21** [comment]
Hello is anyone working on this issue?
I

**Comment by vinzvinci** [comment]
Looks like no one is working here. Are u gonna work for this @unnikrishnan2002 or assign it to Anosh21?

**Comment by Anosh21** [comment]
@vinzvinci I think he's isn't active, You can assign it to me.

**Comment by unnikrishnan2002** [comment]
> Looks like no one is working here. Are u gonna work for this @unnikrishnan2002 or assign it to Anosh21?

No I am not working on it you can assign it to him 👍

**Comment by vinzvinci** [comment]
Done. Thanks for the response.

**Comment by mkubdev** [comment]
I close, will be updated soon with a new footer.
