### ISSUE TITLE
[BUG] Update the website accordingly

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#160]
### Description of the bug

The current website has Web3Community logos and design. We should update the favicon, logos, and design as well.

### Add any other context about the problem here

We might want to update Dev.TO's profile name and logos as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhinavMV** [comment]
There is an upgrade to next.js issue open right.
So maybe these changes can be included in that upgrade too?

**Comment by Panquesito7** [comment]
Yes, that should be done as well. Great catch!

**Comment by KendallDoesCoding** [comment]
This is more of a enhancement than a bug, right? @Panquesito7 Please update the labels

**Comment by KendallDoesCoding** [comment]
A idea for the updation of favicon is #172

**Comment by mkubdev** [comment]
I close, solved with #183
