### ISSUE TITLE
[OTHER] Update the Readme

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#163]
### What would you like to share?

Upgrade the Readme and remove unused chapters.

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marinoffDev** [comment]
Hey 👋🏻 Can I work on this? I can join your Discord to discuss changes as well

**Comment by Panquesito7** [comment]
Hello! This issue is quite old; I'm not sure if it's already fixed or not.
But you can surely improve the readme and write more about WebXDAO. 🙂

Feel free to join our [**Discord server**](https://discord.gg/TSRwqx4K2v) and discuss this.

**Comment by krshkodes** [comment]
Assigned you @marinoffDev! 😀

**Comment by shuklaritvik06** [comment]
Any update on this @marinoffDev

**Comment by vinzvinci** [comment]
Let's continue this after setting up the v3

**Comment by mkubdev** [comment]
Closing.
