### ISSUE TITLE
[FEATURE] 2.0 WebX DAO website

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#164]
### Detailed description

Update the website with this figma design 

https://www.figma.com/file/q2edCdc71T7V2mNANM67dV/WebX-DAO?node-id=0%3A1

please don't mind the team page, only focus on the landing pageFigma

### Context

It would be great to rebrand our site now or later xD

### Possible implementation

CC @hyomiTheTech

### Additional information

We are using Next.js for this https://github.com/WebXDAO/WebXDAO.github.io/pull/162

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hyomiTheTech** [comment]
I am excited to work on my very first assignment!

**Comment by vinzvinci** [comment]
> I am excited to work on my very first assignment!

Thank you, assigned this to you.

**Comment by mkubdev** [comment]
Awesome design @vinzvinci ! Can't wait to see it online. 
Good luck with your PR @hyomiTheTech ! Don't hesite to reach us on discord for any kind of help.

**Comment by hyomiTheTech** [comment]
@mkubdev will do! I will make frequent PR so that you guys can review my code often.

**Comment by mkubdev** [comment]
> @mkubdev will do! I will make frequent PR so that you guys can review my code often.

Count on me!

**Comment by mkubdev** [comment]
Info: figma link ins't available
