### ISSUE TITLE
[BUG] Error in Console

### ISSUE THREAD

**Issue by KendallDoesCoding** [WebXDAO/WebXDAO.github.io#166]
### Description of the bug

Errors in console

### Add any other context about the problem here

```
Unchecked runtime.lastError: The message port closed before a response was received.
webxdao.github.io/:1 
Unchecked runtime.lastError: The message port closed before a response was received.
webxdao.github.io/:1 
Unchecked runtime.lastError: The message port closed before a response was received.
webxdao.github.io/:1 
Unchecked runtime.lastError: The message port closed before a response was received.
about:blank:1 
Unchecked runtime.lastError: The message port closed before a response was received.
about:blank:1 
Unchecked runtime.lastError: The message port closed before a response was received.
about:blank:1 Unchecked runtime.lastError: The message port closed before a response was received.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Can you please provide context and screenshot ?
This landing will be updated to nextjs framework asap. I add `invalid` tag.

**Comment by KendallDoesCoding** [comment]
> Can you please provide context and screenshot ? This landing will be updated to nextjs framework asap. I add `invalid` tag.

Will share in a bit.

**Comment by KendallDoesCoding** [comment]
![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)

**Comment by mkubdev** [comment]
> ![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)

Can't reproduce. Look like and extension issue on your side.. I close 👍🏻

**Comment by KendallDoesCoding** [comment]
> > ![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)
> 
> Can't reproduce. Look like and extension issue on your side.. I close 👍🏻

Ok thanks. My extensions have been interfering with many sites, so thought so but for most of the sites it doesn't show stuff like "webxdao.github.io/:1". Here, it was letting me see where the issue was but it wasn't any code related to the project, I don't think so

**Comment by mkubdev** [comment]
> > > ![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)
> > 
> > 
> > Can't reproduce. Look like and extension issue on your side.. I close 👍🏻
> 
> Ok thanks. My extensions have been interfering with many sites, so thought so but for most of the sites it doesn't show stuff like "webxdao.github.io/:1". Here, it was letting me see where the issue was but it wasn't any code related to the project, I don't think so

Try disable all your extensions, it will not show this error again. It's [FloC related](https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/)

**Comment by KendallDoesCoding** [comment]
> > > > ![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)
> > > 
> > > 
> > > Can't reproduce. Look like and extension issue on your side.. I close 👍🏻
> > 
> > 
> > Ok thanks. My extensions have been interfering with many sites, so thought so but for most of the sites it doesn't show stuff like "webxdao.github.io/:1". Here, it was letting me see where the issue was but it wasn't any code related to the project, I don't think so
> 
> Try disable all your extensions, it will not show this error again. It's [FloC related](https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/)

I have too many extensions, so I'm not in the mood to disable all of them, but yeah ig that will solve the problem. Thanks for your help!

**Comment by mkubdev** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)
> > > > 
> > > > 
> > > > Can't reproduce. Look like and extension issue on your side.. I close 👍🏻
> > > 
> > > 
> > > Ok thanks. My extensions have been interfering with many sites, so thought so but for most of the sites it doesn't show stuff like "webxdao.github.io/:1". Here, it was letting me see where the issue was but it wasn't any code related to the project, I don't think so
> > 
> > 
> > Try disable all your extensions, it will not show this error again. It's [FloC related](https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/)
> 
> I have too many extensions, so I'm not in the mood to disable all of them, but yeah ig that will solve the problem. Thanks for your help!
![image](https://user-images.githubusercontent.com/50140834/154266281-280594f1-51ca-4bc6-8007-17d17587d1da.png)

Maybe you can try to add a new google chrome profil without extension (or use visitor mode), which you will use to do testing.

**Comment by KendallDoesCoding** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/84712013/154260437-218a7624-b1b6-4f4f-97e0-283d73d92b41.png)
> > > > > 
> > > > > 
> > > > > Can't reproduce. Look like and extension issue on your side.. I close 👍🏻
> > > > 
> > > > 
> > > > Ok thanks. My extensions have been interfering with many sites, so thought so but for most of the sites it doesn't show stuff like "webxdao.github.io/:1". Here, it was letting me see where the issue was but it wasn't any code related to the project, I don't think so
> > > 
> > > 
> > > Try disable all your extensions, it will not show this error again. It's [FloC related](https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/)
> > 
> > 
> > I have too many extensions, so I'm not in the mood to disable all of them, but yeah ig that will solve the problem. Thanks for your help!
> > ![image](https://user-images.githubusercontent.com/50140834/154266281-280594f1-51ca-4bc6-8007-17d17587d1da.png)
> 
> Maybe you can try to add a new google chrome profil without extension (or use visitor mode), which you will use to do testing.

Will do.

**Comment by KendallDoesCoding** [comment]
Yup, error doesn't show up in Guest Mode too.
