### ISSUE TITLE
[BUG] Error with permissions on incognito 

### ISSUE THREAD

**Issue by KendallDoesCoding** [WebXDAO/WebXDAO.github.io#169]
### Description of the bug

Error with permissions on incognito

### Add any other context about the problem here

Console Log

```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
![image](https://user-images.githubusercontent.com/50140834/154263901-9e7298eb-3cb5-4acc-ad60-13a2d0bd4030.png)


Hi, thanks.
Can't reproduce on localhost and incognito...
As mentionned [here](https://stackoverflow.com/questions/69619035/error-with-permissions-policy-header-unrecognized-feature-interest-cohort) : `Basically you can ignore it. GitHub hosted pages disable FLoC, which is Google's 3rd party cookie alternative. GitHub, Microsoft, doesn't seems to like it.`

More informations: https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/

I close :)

**Comment by KendallDoesCoding** [comment]
> ![image](https://user-images.githubusercontent.com/50140834/154263901-9e7298eb-3cb5-4acc-ad60-13a2d0bd4030.png)
> 
> Hi, thanks. Can't reproduce on localhost and incognito... As mentionned [here](https://stackoverflow.com/questions/69619035/error-with-permissions-policy-header-unrecognized-feature-interest-cohort) : `Basically you can ignore it. GitHub hosted pages disable FLoC, which is Google's 3rd party cookie alternative. GitHub, Microsoft, doesn't seems to like it.`
> 
> More informations: https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/
> 
> I close :)

Ok cool!
