### ISSUE TITLE
[FEATURE] Update favicon

### ISSUE THREAD

**Issue by KendallDoesCoding** [WebXDAO/WebXDAO.github.io#172]
### What would you like to share?

I had a complaint with the current favicon ( #171 ) and was considering ideas for a suggestion of change of favicon. The favicon can be this which is in the pfp of the organization.

![image](https://user-images.githubusercontent.com/84712013/154261806-769afb38-283d-49d1-a825-085e61170a2e.png)

### Additional information

If yall like the idea, I can work on this.

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuklaritvik06** [comment]
We are currently working on our website with new design etc :) It will be fixed, thank you for opening an issue

**Comment by KendallDoesCoding** [comment]
> We are currently working on our website with new design etc :) It will be fixed, thank you for opening an issue

Yup, #160 says that too, Saw that after I made this issue though.
