### ISSUE TITLE
[BUG] Krish Gupta's pfp on mods page hidden.

### ISSUE THREAD

**Issue by KendallDoesCoding** [WebXDAO/WebXDAO.github.io#173]
### Description of the bug

@krshdev pfp on the mods page isn't showing up.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/84712013/154262422-ccbc5fa3-15dd-4d3b-935f-d1c647f38662.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KendallDoesCoding** [comment]
I think I know a possible reason of this issue. Will have a look.

**Comment by KendallDoesCoding** [comment]
Yup, found the problem.. Making a PR to resolve.

**Comment by shuklaritvik06** [comment]
krshdev new username of krish :)

**Comment by KendallDoesCoding** [comment]
> krshdev new username of krish :)

Yeah, that's exactly what I found..

**Comment by KendallDoesCoding** [comment]
The issue doesn't seem to be fixed with #176 unless the website didnt get deployed with the commit

@shuklaritvik06 Please reopen.

**Comment by mkubdev** [comment]
New landing page is ready. We will fix this issue in the new landing..

**Comment by KendallDoesCoding** [comment]
> New landing page is ready. We will fix this issue in the new landing..

ok!
