### ISSUE TITLE
[OTHER] Remove extra line from Krish's bio

### ISSUE THREAD

**Issue by KendallDoesCoding** [WebXDAO/WebXDAO.github.io#175]
### What would you like to share?

If the bio ends there, it's understood that it's over, there's no need to say "that's my complete bio" 😆

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuklaritvik06** [comment]
Will be discussed with krish and fixed if he want in our new website :) Thank you for opening an issue

**Comment by KendallDoesCoding** [comment]
> Will be discussed with krish and fixed if he want in our new website :) Thank you for opening an issue

Thanks. I suggest you keep this open with the label, "on-hold" or "to-discuss" though.

**Comment by KendallDoesCoding** [comment]
Although, #174 can remain closed in the discussion stage.

**Comment by KendallDoesCoding** [comment]
@mkubdev Thanks, please reopen the issue.
