### ISSUE TITLE
[OTHER] Use a custom domain

### ISSUE THREAD

**Issue by KendallDoesCoding** [WebXDAO/WebXDAO.github.io#178]
### What would you like to share?

It looks more professional when the website is on a custom domain, instead of github pages. Maybe yall can try to get a custom domain after the revamp of the site?

The issue is that webxdao.com is for a massive massive price on any domain buying service, just look at this:
Namecheap: ₹740,209.17/yr (9,856.91 USD)
Godaddy:  ₹17,30,526.32/yr (23044.35 USD)

But, as this is a organization maybe yall can try to get .org, cause those prices seem reasonable:
Namecheap: ₹678.27/yr (9.03 USD)
Godaddy: It's usually ₹ 1,399.00 but it's on discount now, but for the first year it's only ₹ 99.00 which comes to about (1.32 USD)

So yeah, I think consider getting a .org domain, cause I don't think it's worth paying such a PREMIUM for .com 😆 

### Additional information

Anyone know's why the .com domain is so expensive? Is it cause the domain as web in it or something? They call the domain webxdao.com, a premium domain.

@EddieHubCommunity uses DigitalOcean for domains I believe, I don't really know their prices but yall can have a look.

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KendallDoesCoding** [comment]
If yall have a domain already, dw about the above, just link it to the Github Pages. If yall need help, I'll be happy to help :)

**Comment by rudrakshkarpe** [comment]
Yes, I do agree with @KendallDoesCoding you guys can simply set up a custom domain using GitHub pages 

![image](https://user-images.githubusercontent.com/78851635/190188369-3e02c539-be53-440a-8b5d-3369ed6cce25.png)

you guys can check this out [here](https://www.namecheap.com/domains/registration/results/?domain=.tech) this looks pretty reasonable from Namecheap,  but after all, with a custom domain, your project will be much better :)

**Comment by mkubdev** [comment]
> Yes, I do agree with @KendallDoesCoding you guys can simply set up a custom domain using GitHub pages
> 
> ![image](https://user-images.githubusercontent.com/78851635/190188369-3e02c539-be53-440a-8b5d-3369ed6cce25.png)
> 
> you guys can check this out [here](https://www.namecheap.com/domains/registration/results/?domain=.tech) this looks pretty reasonable from Namecheap, but after all, with a custom domain, your project will be much better :)

Sure, good idea!

**Comment by KendallDoesCoding** [comment]
> Yes, I do agree with @KendallDoesCoding you guys can simply set up a custom domain using GitHub pages
> 
> ![image](https://user-images.githubusercontent.com/78851635/190188369-3e02c539-be53-440a-8b5d-3369ed6cce25.png)
> 
> you guys can check this out [here](https://www.namecheap.com/domains/registration/results/?domain=.tech) this looks pretty reasonable from Namecheap, but after all, with a custom domain, your project will be much better :)

actually, .tech and many other domains are free on the GitHub student plan

.tech, .me, and MANY others, I'm sure y'all are aware of it.

**Comment by krshkodes** [comment]
Hi, any updates?

**Comment by KendallDoesCoding** [comment]
I think .tech would be best for this org

btw @krshkodes , please reach out to me urgently.

**Comment by krshkodes** [comment]
@WebXDAO/core-maintainer

**Comment by mkubdev** [comment]
We already have a domain for the org @krshkodes

**Comment by krshkodes** [comment]
Yes I know about that, the xyz one, I mean, is this issue fixed or shall I?

**Comment by mkubdev** [comment]
> Yes I know about that, the xyz one, I mean, is this issue fixed or shall I?

You are mod, we talked about it in the mod discord ! Kindly suggest you check the channels.

**Comment by shuklaritvik06** [comment]
We have a custom domain now https://webxdao.xyz and also we are verified org now :)
