### ISSUE TITLE
invite me to organization

### ISSUE THREAD

**Issue by MetaMars0114** [WebXDAO/WebXDAO.github.io#188]
### What would you like to share?

I want join your team.

### Additional information

I am a game developer

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hi @MetaMars0114 :wave:

You should raise an issue here to get invited to the community: https://github.com/WebXDAO/start-here

I close
