### ISSUE TITLE
[BUG] Various website issues

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#192]
### Description of the bug

There are a few website issues that should be fixed immediately.
Here is a list that includes most of the issues on the website.

- The GitHub button is not working. It should lead to our GitHub organization.
- Probably add another link in the Hacktoberfest part instead of our GitHub organization, as it's already linked in other parts various times.
- Fix all the footer links to link to their respective sites.
- The community partners page should be updated to match the new design.
- The blog, projects, and the WebX team pages should be made/updated.
- Add a link to the website in WebXDAO's logo to make it easier to go to the homepage.
- Make a partner form, so that other communities can become partners with us.
- Make an about us page. This way, people that come and check our website will know what we do, what projects we have, tools, resources, etc., etc..

If I missed anything, please let me know in the comments below. 🙂

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
I take the issue! Will PR in the next few days

**Comment by mkubdev** [comment]
@Panquesito7 I suggest to open one issue per issues mentionned above tagged with hacktoberfest?

**Comment by mkubdev** [comment]
I close, created issues related to this one. 😊

**Comment by krshkodes** [comment]
Hi, why does a closed issue have a hacktoberfest label added after it was closed? 🤔 No worries though, now it is all cool!
