### ISSUE TITLE
[FEATURE] Add contributors page

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#193]
### Detailed description

Maybe let's show our contributors in our website like this https://www.4c.rocks/contributors

### Context

Idk, maybe just to share our contributors profile and encourage more folks to contribute with our projects.

### Additional information

Put this on-hold for hacktoberfest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
That's always a cool feature to show to the community! ⚡

# Steps

1. Create a new page `contributors` at `src/pages/contributors.js`
2. Fetch the the contributors:
   * Use **[getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props)** as data fetching method
   * You can test the github API from cli with `gh api repos/WebXDAO/webXDAO.github.io/contributors`
   
![image](https://user-images.githubusercontent.com/50140834/192231253-09c452b1-8799-4373-87e8-36aafb0a300c.png)

3. Create a card component (or another display if you think it's fit better) and use the json payload from GitHub API to display the repository contributors.

**Comment by Asmit2952** [comment]
Can I work on this?

**Comment by Anuran12** [comment]
Hi I would like to contribute. Could you please assign it to me? I need to do this for Hacktober 2022.

Thanks : )

**Comment by vinzvinci** [comment]
> Hi I would like to contribute. Could you please assign it to me? I need to do this for Hacktober 2022.
> 
> Thanks : )

Okay cool, please don't submit any PR for now. You can submit when hacktoferbest start

**Comment by Anuran12** [comment]
@vinzvinci hi I added "contributors page" in my fork. please check it out. 

https://github.com/Anuran12/WebXDAO.github.io.git

I added this in a separate branch called "contributors-page". please check that and give me feedback. if you want to change or add something you can tell me.

Thanks :

**Comment by mkubdev** [comment]
@Anuran12 Hi :wave: ! Hacktoberfest start 1st October 2022, every PR sent before will not count as Hacktoberfest contribution.

Kindly suggest you to open a PR the starting day with your changes. 👍🏻 
Btw, I read your work for `/contributors`, that look good to me ✌ But we use [TailwindCSS](https://tailwindcss.com) for styling!

**Comment by Anuran12** [comment]
@mkubdev So do I have to change the style from css to tailwind css ?

I am not familiar with tailwind css : (

**Comment by mkubdev** [comment]
@Anuran12 No, you can keep it if it's fit the global layout!

**Comment by Anuran12** [comment]
Ok thanks 😊
@mkubdev  @vinzvinci 

If you need more features in the website. I can help you . Just create more issues.. i will check them out.

**Comment by mkubdev** [comment]
> Ok thanks 😊 @mkubdev @vinzvinci
> 
> If you need more features in the website. I can help you . Just create more issues.. i will check them out.

Hey, yeah sure, we'll open more issue tonight!

**Comment by vinzvinci** [comment]
Yes! more issues, more fun! Thank you @Anuran12 🎉

**Comment by Panquesito7** [comment]
> Hey @vinzvinci can i create the PR now ?

I'd wait until Hacktoberfest starts so that it counts towards your progress in the event. :)

**Comment by vinzvinci** [comment]
Hacktoberfest is live now for ASIA region @Anuran12

 I know you're super excited! Feel free to open PR now :)

**Comment by Anuran12** [comment]
@vinzvinci I created a PR. Please check it out
