### ISSUE TITLE
[BUG] Header button is not clickable

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#194]
### Description of the bug

Hi, the logo inside the navbar not working. It should redirect to `/`

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/50140834/193082445-ff21cfbf-eaf1-45a0-b94c-0a304ecfe70e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ahmedsilat44** [comment]
@mkubdev Could you assign me this issue. I would like to try to fix this bug. Thanks 😄

**Comment by Panquesito7** [comment]
> @mkubdev Could you assign me this issue. I would like to try to fix this bug. Thanks 😄

Thanks for your interest in contributing! Feel free to make a PR.
Any questions, doubts, or anything else, let us know! 🙂
