### ISSUE TITLE
[FEATURE] Update the community partners page

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#195]
### Detailed description

Update the page to fit the new design :

* background should be `transparent`
* text should be `text-white/80`

![image](https://user-images.githubusercontent.com/50140834/193083127-1579083f-6153-4dbf-afb6-ff8981d4edde.png)

We should add:
* DevProtocol
* theAlgorithms
* LumosLabs

### Context

It's better if we can match the landing design.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hackobansa** [comment]
Good day @mkubdev  please assign me to this issue

**Comment by Panquesito7** [comment]
> Good day @mkubdev please assign me to this issue

Thanks for your interest in contributing! Feel free to make a PR.
Any questions, doubts, or anything else, let us know and we'll help! 🙂

**Comment by hackobansa** [comment]
thank you so much for assiging me

**Comment by hackobansa** [comment]
can i add dev protocool alternatives

**Comment by hackobansa** [comment]
@vinzvinci @Panquesito7 @mkubdev  im done

**Comment by Panquesito7** [comment]
> @vinzvinci @Panquesito7 @mkubdev im done

Nice! Feel free to make a PR for it. 🙂

**Comment by mkubdev** [comment]
Do you need help with your PR @Web3Ctrl ?

**Comment by Web3Ctrl** [comment]
Yes

**Comment by Anuran12** [comment]
@mkubdev  hey is this issue still open? Then i would like to work on this

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/195809189-9b19bd47-f5fe-4b50-b379-6d3b94e0d5d1.png)

Is it looking good ? I change things according to other pages.

**Comment by mkubdev** [comment]
Awesome 👍🏻
