### ISSUE TITLE
[FEATURE] Update the blog page

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#196]
### Detailed description

Blog page should be updated to match the new design :

* background should be `bg-transparent`
* text should be `text-white/80`

![image](https://user-images.githubusercontent.com/50140834/193083541-9478bab9-dc0c-44ae-9ebf-da2b9d785517.png)

### Context

Actually it's showing nothing, maybe we can request WebXDAO dev.to articles from https://dev.to/webxdao and show them as cards ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anuran12** [comment]
@mkubdev Can I work for this too ?

**Comment by mkubdev** [comment]
Sure, i assigned you ! :)

**Comment by Anuran12** [comment]
But i have a doubt. If i make PR for 2 issues in same repository then Does both count or does one counts?

**Comment by mkubdev** [comment]
> But i have a doubt. If i make PR for 2 issues in same repository then Does both count or does one counts on hacktoberfest website?

You should make a PR per issue to get both counted for hacktoberfest :)

**Comment by krshkodes** [comment]
Hi @Anuran12, I would suggest you use tailwind, but in this case, you can use CSS, I'll later convert it tailwind in another pr

**Comment by Anuran12** [comment]
@krshkodes   Yesterday I learned tailwind css and did it with that. so you don't have to do this.. Hahaa 😅

this is my first time open source contribution.. I am learning so many things with this which are really fun....

THANKS all members 🙏

I will make the PR soon...

**Comment by krshkodes** [comment]
Wow, awesome! Congrats @Anuran12

**Comment by Anuran12** [comment]
@mkubdev I created the PR . Please check it out
