### ISSUE TITLE
[FEATURE] Build a partner form component

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#197]
### Detailed description

We should build a nextjs form component to let other communities become partners with us.

### Context

Maybe using Formspree or Typeform could be more simple for GitHub Page?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krshkodes** [comment]
I would use Google forms

**Comment by mkubdev** [comment]
> I would use Google forms

Yup, good idea Google forms is pretty simple to setup.
