### ISSUE TITLE
[FEATURE] Build an about us page

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#198]
### Detailed description

This way, people that come and check our website will know what we do, what projects we have, tools, resources, etc., etc..

### Context

The page should be called `/about-us` and respect the initial design.

To create section, use `bg-transparent` and `text-white/80` on parent div to show the global gradient background.

### Possible implementation

We should collaborate on a Figma or panpot file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clairecharles** [comment]
Hey @mkubdev can i work on this issue?

**Comment by mkubdev** [comment]
Hey @clairecharles 👋🏻 ! Sure, i assign you :D

**Comment by clairecharles** [comment]
Hey, @mkubdev to be able to make the about page I would need a brief summary of what the project is about and what the mission is. If possible, the projects built and to be built.

I need this information to be able to make a pr, that because I am not a member of the team.
I would be so glad if you provide the information :)

**Comment by mkubdev** [comment]
> Hey, @mkubdev to be able to make the about page I would need a brief summary of what the project is about and what the mission is. If possible, the projects built and to be built.
> 
> I need this information to be able to make a pr, that because I am not a member of the team. I would be so glad if you provide the information :)

Hi @clairecharles ! ✨✌
Sure, this issue is a bit confusing and not well detailed.

## Who we are ?

WebXDAO is an opensource community that focus on the future of the web. Here you will learn how to become a blockchain developer while having fun with other community members. Blockchain Developer is an interesting field, in demand and the latest trend in the tech industry. Here you will get to interact with some great folks and learn blockchain technology together. This community is in its initial stage so you can show your leadership skills and help for everyone's success.

## The mission ?

Our goal is to build a team of passionate builders around web technologies. We like sharing knowledge as much as we can and grow together. 

## Technical Stack 🔧

* This website is built with [Next.js](https://nextjs.org/) framework.
* We use [TailwindCSS](https://tailwindcss.com/) as CSS framework.
   * As mentioned earlier, you just need to use `bg-transparent` and `text-white/80` in the parent div to match the current design!

## Summary

* You can start by creating a page : `pages/about-us`
* I suggest to create one first section containing the Who we are? content
* A second section containing the The mission? content

We don't have composition requirements so be free to propose what you want/like. 🎨

Thanks a lot for your interest! 🌠
