### ISSUE TITLE
[FEATURE] Automate build on every change

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#200]
### Detailed description

I think it's cool if we add this as well. I provided the information below (Context)

### Context

All examples and context here:
https://github.com/dailydotdev/docs/issues/124

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krshkodes** [comment]
Can I work on this?

**Comment by vinzvinci** [comment]
Sure @krshkodes!
