### ISSUE TITLE
[FEATURE] SEO Optimization

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#202]
### Detailed description

Need to add Meta Information, Opengraph, etc.

### Context

We know this is very important for the website :) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ishaanbedi** [comment]
I'd like to work on this! Can you please assign it to me?

**Comment by mkubdev** [comment]
I suggest to use [next-seo](https://github.com/garmeeh/next-seo) for this task. 😃

**Comment by shuklaritvik06** [comment]
Great Suggestion @mkubdev  🔥

**Comment by shuklaritvik06** [comment]
> I'd like to work on this! Can you please assign it to me?

Cool Assigning you, Go Ahead 🚀

**Comment by ishaanbedi** [comment]
> > I'd like to work on this! Can you please assign it to me?
> 
> Cool Assigning you, Go Ahead 🚀

Alright! Working on it...

**Comment by krshkodes** [comment]
Awesome! Happy Hacktoberfesting 🚀

**Comment by vinzvinci** [comment]
Closing this issue now.
