### ISSUE TITLE
[FEATURE] Containerize app with docker

### ISSUE THREAD

**Issue by harshit0571** [WebXDAO/WebXDAO.github.io#205]
### Detailed description

we can containerize this project using docker compose.

### Context

the entire project can be run using `docker-compose up` command.
if someone has not installed nodejs or is using a different version of it , the project may not run on his system by using `npm run dev`
so docker can help

### Possible implementation

create a Dockerfile and Docker-compose file to run container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krshkodes** [comment]
👍 Great idea, would you like to work on it or it is up for grabs?

**Comment by harshit0571** [comment]
i would like to work on it

**Comment by krshkodes** [comment]
Sure! Assigned to you

**Comment by mkubdev** [comment]
I close, #208 solve this.
