### ISSUE TITLE
[FEATURE] Improve Meta data in package.json file

### ISSUE THREAD

**Issue by Pradumnasaraf** [WebXDAO/WebXDAO.github.io#214]
### Detailed description

Metadata that is missing.

```
  "repository": {
    "type": "",
    "url": ""
  },
  "keywords": [
  ],
  "author": "",
  "license": "",
  "bugs": {
    "url": ""
```
### Context

Good for searchability on GitHub, and give more context about the project

- [X] I agree to follow this project's Code of Conduct

**Comment by krshkodes** [comment]
Thank you for pointing out pradumna! Would you like to work on this?

**Comment by Pradumnasaraf** [comment]
> Thank you for pointing out pradumna! Would you like to work on this?

Yes sure 👀
