### ISSUE TITLE
[FEATURE] responsiveness of Projects page

### ISSUE THREAD

**Issue by void-ness** [WebXDAO/WebXDAO.github.io#216]
### Detailed description

The Current Projects page is not responsive. Overall it leaves a bad impression to first-time users of the website. Considering a lot of people will be accessing the website via their mobiles, The mobile version of the website should be at par with the desktop version. Few problems in the current design are:

![image](https://user-images.githubusercontent.com/78547746/193450165-f6b3e9d8-0ae3-48d3-8ae9-ba7ffd754a1c.png)
(Page Description box is overflowing, out of the screen)

![image](https://user-images.githubusercontent.com/78547746/193450201-f946b6ad-1110-4b12-b97c-bc941221c593.png)
(The project cards are very large in size from what they should be in phone view)

![image](https://user-images.githubusercontent.com/78547746/193450252-6644de89-2688-4395-9450-2f5e4873bed0.png)
(the footer will look better if the text is left aligned)

![image](https://user-images.githubusercontent.com/78547746/193450268-bad48c56-cfd1-4aea-b491-07ac70133604.png)
(Due to few overflowing-div above, the footer is not able to fill all the screen area)

### Context

Having a responsive design will make the website more mobile friendly. Along with improving the overall user-experience it will help in improving the SEO metrics of the website.

### Possible implementation

![image](https://user-images.githubusercontent.com/78547746/193450356-03affd42-6ce2-4e42-bcc9-7cb852f01ee4.png) 

(No more overflowing content with proper spacing wherever required) 

![image](https://user-images.githubusercontent.com/78547746/193450379-bb629df8-57b8-4fcd-ae77-c5377a72f7bb.png) 
 
(improved card sizing) 

![image](https://user-images.githubusercontent.com/78547746/193450383-1b846ef9-c690-4051-827f-274ab1948ff9.png) 

(Updated footer with all the text elements aligned to the left)

### Additional information

- [x] Do you want to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by void-ness** [comment]
I would love to work on this issue and do the concerned changes using Tailwind classes. Kindly assign it to me

**Comment by vinzvinci** [comment]
Thanks! Would love to see your work @void-ness !
