### ISSUE TITLE
[BUG] There's no way to go back home from other pages 

### ISSUE THREAD

**Issue by Johnnyteck** [WebXDAO/WebXDAO.github.io#218]
### Description of the bug

Would love to help with including a home link in the mav so visitors can easily click that to return to the homepage of the website or the website logo, just a link that users can intuitively click and would bring them to the homepage of the website 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by void-ness** [comment]
I would love to work on this. 

We can hyperlink the logo in navbar to point it to home. For the footer section we can add another link "home" under the about us section pointing back to the landing page.

**Comment by mkubdev** [comment]
@Johnnyteck Your issue was legit, why close?

**Comment by Anuran12** [comment]
@mkubdev can i give it a try ?

**Comment by Johnnyteck** [comment]
ooh sorry, that was a mistake. I was clearing my issues tab and clicked this instead of another. Just realizing this now

**Comment by Johnnyteck** [comment]
Yes, @mkubdev you can assign me

**Comment by vinzvinci** [comment]
Hi @Anuran12, I'm assigning this to @Johnnyteck since he created this issue. Feel free to raise other issue @Anuran12
