### ISSUE TITLE
[FEATURE] Add prettier github action

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#221]
### Detailed description

It is best to format our code with Prettier GitHub action when someone create PR

### Context

Since some folks having issue with single quote and double quote like this https://github.com/WebXDAO/WebXDAO.github.io/pull/191

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
I take this one! ⚡

**Comment by vinzvinci** [comment]
Thanks @mkubdev! Assigned ✅
