### ISSUE TITLE
[FEATURE] Replace Prettier GitHub action by Eslint

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#226]
### Detailed description

In #223, @krshkun suggests using eslint to replace prettier. 

### Context

Replace the GitHub prettier action `prettier.yml`

### Possible implementation

We can implement:

* husky pre-commit: https://github.com/typicode/husky
* Or replace the prettier with eslint 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hello @siddoinghisjob ! I think @krshkun will be more suitable to guide you than me for this task.
Btw, i just opened a new issue #230 if you want. :)

**Comment by krshkun** [comment]
@siddoinghisjob, if you'd like to do this issue - I have absolutely no issues in guiding you, sinc @mkubdev linked to another issue, please affirm which one you'll be working on
