### ISSUE TITLE
[Bug] The project page and partners page are not responsive at mobile view

### ISSUE THREAD

**Issue by Anuran12** [WebXDAO/WebXDAO.github.io#228]
### Description of the bug

The project page and the partners page are not looking good in mobile view. I can fix it by using tailwind breakpoints.

### Please add screenshots (if applicable)

![Screenshot_2022-10-05-21-58-24-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/104062485/194114732-19a33777-93e9-4b11-b307-5fc1b95da8f1.jpg)
![Screenshot_2022-10-05-21-58-36-60_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/104062485/194114756-5ac681a9-dfc3-4c6e-bceb-31494d88a739.jpg)
![Screenshot_2022-10-05-21-58-47-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/104062485/194114842-559a3130-8db0-48d6-802b-b8bf5a248ae2.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by void-ness** [comment]
Hey, #219 deals with the responsiveness of projects page. It's pending to be merged as of now

**Comment by mkubdev** [comment]
Hi @Anuran12 ! #219 fixed the responsive!

Let's chat on the discord to see what issue we can open here! :smile:

**Comment by Anuran12** [comment]
@mkubdev OK.. 😁

**Comment by Anuran12** [comment]
Hey..... @mkubdev Please add "hacktoberfest" label and "hacktoberfest-accepted" label
