### ISSUE TITLE
[FEATURE] Redirect to our github organization

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#230]
### Detailed description

We should add a destination to this button :
![image](https://user-images.githubusercontent.com/50140834/194288558-39b0af95-fb3e-4c4e-b209-3e36dd4a9de5.png)

### Context

This button is displayed but do nothing.

### Possible implementation

Use this snippet in the file `src/components/Global/Navbar.js` Line 56:

```html
// Update the href above!

<a
  href="#" 
  className="inline-flex items-center px-4 py-2 text-base font-medium text-gray-600 bg-gray-100 border border-transparent rounded-md hover:text-white/80 hover:bg-gray-700"
>
  GitHub
  <SiGithubsponsors className="w-5 h-5 ml-3 text-pink-600" aria-hidden="true" />
</a>
```

* Link of the organization is: https://github.com/WebXDAO

Use this link for the `href` param.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by najeebkp** [comment]
hi @mkubdev please assign to me

**Comment by siddoinghisjob** [comment]
I want to work on this. Can you assign me this issue?

**Comment by Anuran12** [comment]
@siddoinghisjob  Hi.. sorry this issue is already done by @najeebkp  the maintainers did not Marge this for some reason. You can find another issue or you can make an issue . Thanks

**Comment by shuklaritvik06** [comment]
> @siddoinghisjob  Hi.. sorry this issue is already done by @najeebkp  the maintainers did not Marge this for some reason. You can find another issue or you can create an issue . Thanks 

Thank you Anuran, You are doing great work!
@siddoinghisjob PR is already made and is on hold as the GitHub sponsors url is not yet ready for our org. You can refer to the discussion on that PR for more info :)

**Comment by vinzvinci** [comment]
This is already done! Thanks!
