### ISSUE TITLE
[FEATURE] Fixing Navbar to top

### ISSUE THREAD

**Issue by void-ness** [WebXDAO/WebXDAO.github.io#242]
### Detailed description

The position of the navbar is currently not fixed on the phone. When a user scrolls down to to the bottom and wants to access the menu, they need to scroll back to the top thus leading to a comparatively poor user experience. 

### Context

Having a navbar fixed to the top will make sure that the menu is always available to be used by the user as should be the case. Also by fixing the navbar, the community logo inside it also stays visible throughout the user is visiting the website.

### Possible implementation

- [x] by changing the position property of the header to fixed using appropriate tailwind classes.
- [x] Updating the background color of header with a blur filter to produce a better visual effect.  

### Additional information

<div> 

<img src="https://user-images.githubusercontent.com/78547746/194550391-ca9e305f-c4bf-44af-92ae-c9b983276f36.png" height=400 /> 

<img src="https://user-images.githubusercontent.com/78547746/194550545-cb1c27a2-c963-4e86-961a-49ac4afba3e9.png" height=400 />

<img src="https://user-images.githubusercontent.com/78547746/194550816-5b61ab1f-9c5e-432d-bb83-ae58c5b7d795.png" />

</div>

- [x] Would you like to work on this issue?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hi! Super cool feature. ✨
But this one is tricky!

* The `<Hero/>` component need a top margin to not be hidden by the fixed navbar
* We would like to keep the navbar with a base `bg-transparent`, and trigger the blur effect only on scroll! So that the hero will look the same as now when we enter on the website.
* I'm not sure of the UI in mobile once the mobile menu is opened?..

**Comment by void-ness** [comment]
Hey! 

-  I took into account the top margin part. Will do that.
-  Having the `bg-transparent` made the white logo disappear when the navbar overlaps an element with a white bg. Attaching a photo below to better explain that. 
  
<img src="https://user-images.githubusercontent.com/78547746/194582266-4c9b1a30-c2eb-40a6-a71c-c54612c005a0.png" height=400 />

To account for that, I was planning to use a gradient similar to the one in BG as I tried to depict through the photos attached in the issue above. Here's an image how the updated navbar may look at top with no scroll.

<img src="https://user-images.githubusercontent.com/78547746/194600477-b6ac25b4-04e6-40ba-975b-80f953cc550e.png" width=600 /> 
The navbar doesn't look much different in my opinion. We can keep it like this, otherwise trigger the bg change only on scroll as you mentioned above which will involve an additional function tracking the event.

- The mobile menu will work as usual. 
<img src="https://user-images.githubusercontent.com/78547746/194601056-f39c6923-5eb4-41d9-bb42-92e5912bb9f3.png" height=400 />

Let me know, If I was able to answer your questions or if you have any more :)

**Comment by mkubdev** [comment]
Hi @void-ness, let me develop the navbar to test locally. We can inject different classes depending on the event, I don't think the logo disappears with bg-transparency (i mean there is already a bg-transparency in the navbar component!).

I keep you in touch 🔧

**Comment by vinzvinci** [comment]
It looks like the issue is related to the old website design. Please create a new issue for the updated design. 

Thanks for coming here!
