### ISSUE TITLE
[FEATURE]New logo proposal

### ISSUE THREAD

**Issue by tarunfy** [WebXDAO/WebXDAO.github.io#243]
### Detailed description

After going through the weird logo issue we are facing, I created a SVG version of the original .png logo in Figma. 

I request everyone to give feedback and tell us whether we should replace the original .png logo with it or not. 

Here is the new [Logo](https://drive.google.com/file/d/1j4dG_G4NkbP7AFMJ0lErv77am5wXiyom/view?usp=sharing) please give it a look.

Thanks 😊

### Context

Recently I saw some issues related to our logo being stretched when exposed to large sizes and sometimes being too small and blurry.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
We have new logo coming! Thanks!
