### ISSUE TITLE
[BUG] navbar logo is not showing 

### ISSUE THREAD

**Issue by Anuran12** [WebXDAO/WebXDAO.github.io#244]
### Description of the bug

Somehow navbar logo is not showing

![Screenshot_2022-10-07-17-55-16-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/104062485/194552902-fb6b43fc-b3d5-4b73-86e3-2911689096a5.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
It look like the filename has changed since the last PR from white_logo.png to logo.png. Do you want to work on it?

**Comment by tarunfy** [comment]
> > > It look like the filename has changed since the last PR from white_logo.png to logo.png. Do you want to work on it?
> > 
> > 
> > I fixed it just creating a PR. Sorry I forgot to change the name there 🫤.
> 
> Ok, but i think we'll add the invalid tag for this PR as it's an extra small changes. 🙈

No worries man :)
