### ISSUE TITLE
[FEATURE]Responsiveness issue for tablet screens

### ISSUE THREAD

**Issue by tarunfy** [WebXDAO/WebXDAO.github.io#247]
### Detailed description

Home page is not responsive on tablet screens like iPad air, etc. 

<img width="1440" alt="Screenshot 2022-10-07 at 7 46 57 PM" src="https://user-images.githubusercontent.com/51208270/194575101-2ca43792-f690-45f4-9dc5-76e5ec4ab37e.png">
^here is how it looks :(

### Context

It can help us improve the UX of our application.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hey, what do you think of keeping the navbar the way it is for ipad/tab :
![image](https://user-images.githubusercontent.com/50140834/194586754-25ffa029-8339-471c-a46c-a9ff133f4cc7.png)

IMO, the only thing to fix is the stretched logo. CC @WebXDAO/core-maintainer

**Comment by tarunfy** [comment]
The problem is that we have too many links in the navbar due to which elements are not able to breathe it's all looking messy, simply it's a bad UI, hope you will understand. Another option is to decrease the font size of the links and decrease the size of the logo but that will still make it messy.

**Comment by mkubdev** [comment]
Yes, i tested multiple iPad screen sizes and effectively once using the iPad mini size, menu list are messy.

**Comment by tarunfy** [comment]
I have already generated a pr for this issue kindly check :)
