### ISSUE TITLE
[FEATURE] Add `.dockerignore` file

### ISSUE THREAD

**Issue by Pradumnasaraf** [WebXDAO/WebXDAO.github.io#252]
### Detailed description

Adding a `.dockerignore` file and ignoring the files which don't play role in building the image will reduce the build size.

### Context

Fast development and testing

- [X] I agree to follow this project's Code of Conduct

**Comment by Pradumnasaraf** [comment]
I would like to work on this issue. Thank you.

**Comment by mkubdev** [comment]
Hi sure i'll assign you, Pradumna. ✨

**Comment by Pradumnasaraf** [comment]
Thank you!
