### ISSUE TITLE
Footer links are not working & Blog items fonts need correction which doesn't look consistent with other pages typography

### ISSUE THREAD

**Issue by milanshresta** [WebXDAO/WebXDAO.github.io#258]
### What would you like to share?

![footer](https://user-images.githubusercontent.com/115529274/203000324-6dc545e0-42f4-4510-965a-5b9bfd1e6a23.png)

### Would you like to work on this issue?

- [x] Yes, I want to work on this issue!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ShivangShandilya** [comment]
I can work on this if it's still not resolved and if someone can guide me along the way like give me proper links to add, that would be great

**Comment by milanshresta** [comment]
> I can work on this if it's still not resolved and if someone can guide me along the way like give me proper links to add, that would be great

**Comment by milanshresta** [comment]
Yeah, absolutely you can add link. It's not still working.

**Comment by mkubdev** [comment]
@milanshresta Hello! The footer component doesn't add the href from the `navigation` array : https://github.com/WebXDAO/WebXDAO.github.io/blob/2cf878a4805c1b8e1b765f6c76d24f17a7fbfb4a/src/components/Global/Footer.js#L69

* /src/components/Global/Footer.js :
```js
<nav className="mt-4 sm:mt-8" aria-label={item.name}>
                    <ul className="space-y-4 text-sm">
                      {item.children.map((child) => (
                        <li key={child.name}>
                          <Link
                            className="transition text-white/60 hover:text-white/60/75"
                            href=""
                          >
                            <span className="text-white/60">{child.name}</span>
                          </Link>
                        </li>
                      ))}
                    </ul>
                  </nav>
```
