### ISSUE TITLE
Scott

### ISSUE THREAD

**Issue by DevScottMiller** [WebXDAO/WebXDAO.github.io#259]
### What would you like to share?

I am Scott

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuklaritvik06** [comment]
Hey Scott 👋🏼  Any help needed? You can join our [Discord Server](https://discord.webxdao.xyz) , folks there will help you. I am closing this issue, you can continue the discussion there.
