### ISSUE TITLE
[FEATURE] Center the partners if the number of partners is odd

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#264]
### Detailed description

If the number of partners is odd (say, 3), the last partner should be centered for better styling.
Currently, there was a placeholder partner, but that looks unprofessional and we do not want that, IMO.

Something similar to this (couldn't replicate it with the real code).

![image](https://user-images.githubusercontent.com/51391473/232930406-438cebcc-89bc-41a2-8fef-c0ed97fc1892.png)

### Context

This would have a bit more styling as well as no need for a partner placeholder as we were doing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mud1tx** [comment]
@Panquesito7 I can work on this issue easily and complete it by today only. Please assign it to me.

**Comment by mkubdev** [comment]
Hi @mud1tx ! Assigned :) Thanks for your interest. 😋

**Comment by vinzvinci** [comment]
Check the new design here 👉 [Website v3](https://github.com/orgs/WebXDAO/projects/9/views/1?pane=issue&itemId=28110723)

Closing this now. Thanks!
