### ISSUE TITLE
[FEATURE] Center the mods/maintainers team

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#265]
### Detailed description

I believe it would look better if we centered the team of mods and maintainers (same as #264).
What do you think about this? I think it would look better, IMO.

![image](https://user-images.githubusercontent.com/51391473/233144949-cb1b7670-b99e-4558-8a7b-1bf224fa50c9.png)

### Context

This would make the styling look better, in my opinion.
In case more maintainers are added, the design will look better as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArslanYM** [comment]
would love to work on this ?

**Comment by Panquesito7** [comment]
> would love to work on this ?

Assigned! Thanks. 🙂

**Comment by ArslanYM** [comment]
On it
