### ISSUE TITLE
[FEATURE]: Make the /team section better looking

### ISSUE THREAD

**Issue by ArslanYM** [WebXDAO/WebXDAO.github.io#268]
### Detailed description

Would enhance the look of the website if the cards in the /team section were smaller than current size. They are taking too much space of the screen and also thier UI doesnt match the website.

### Context

.

### Additional information

![this](https://user-images.githubusercontent.com/104521101/233781084-4875190c-0107-45ee-b9a4-58c3609582c5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
- I propose removing the card background, and using something like "Glass" looking like `bg-white/20 backdrop-blur-md`.
- Or using a `hover:shadow-md` on the avatar with a [custom shadow color](https://tailwindcss.com/docs/box-shadow-color)?

**Comment by ArslanYM** [comment]
yeah seems like a pretty cool idea

**Comment by Mudassirkhan2** [comment]
if its open  i would definitely like to enhance the look of card.

**Comment by vinzvinci** [comment]
Arslan worked on this: https://github.com/WebXDAO/WebXDAO.github.io/pull/267

but if you have an idea to improve it more @Mudassirkhan2, feel free to create PR!

**Comment by Mudassirkhan2** [comment]
Ok will tell you if I got good idea.

**Comment by vinzvinci** [comment]
Closing this now!
