### ISSUE TITLE
[FEATURE] Add mascot to 404 error page

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#269]
### Detailed description

Meet DeX! Our new designer @mynrjad created our community mascot 🥳 

![DeX](https://user-images.githubusercontent.com/73097560/234593131-62d00914-ac32-4398-9964-b484cedcfa78.png)

### Context

Let's add our mascot just like

https://github.com/top/asd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
We could also add it in other parts of the website (other secret parts, not exactly sure where, though). 🤔

**Comment by ArslanYM** [comment]
would love to add this feature!! Assign me.

**Comment by vinzvinci** [comment]
Our guild designers currently planning that to our upcoming design for main website @Panquesito7

**Comment by vinzvinci** [comment]
> would love to add this feature!! Assign me.

Assigned ✅ looking forward to your contribution;)

**Comment by vinzvinci** [comment]
Hi, if you haven't started this yet, you can wait for the new design of the 404 error page. Thanks!

**Comment by gptkrsh** [comment]
Can we have the eyes have an eyeball animation on the 404 page? Like this: https://codepen.io/gptkrsh/pen/RwYbyvP

**Comment by mkubdev** [comment]
> Can we have the eyes have an eyeball animation on the 404 page? Like this: https://codepen.io/gptkrsh/pen/RwYbyvP

This is very cool !!

**Comment by MAYANKpandey14** [comment]
Nice idea to add animation. Will look very cool.

**Comment by Vidip-Ghosh** [comment]
I would like to work on this

**Comment by vinzvinci** [comment]
Hey, the [404 page](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=1023-2103&t=4d4IJPPeJAZvJapC-0) is finished, you can start working on this now: 
![404 Error Page](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/d305a0b4-072a-4183-90a8-200bceaa98e5)

**Comment by Vidip-Ghosh** [comment]
> Hey, the [404 page](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=1023-2103&t=4d4IJPPeJAZvJapC-0) is finished, you can start working on this now: ![404 Error Page](https://user-images.githubusercontent.com/73097560/243292804-d305a0b4-072a-4183-90a8-200bceaa98e5.png)

Okay, if any work is remaining, can I work?

**Comment by PatilHarshh** [comment]
@vinzvinci I am intrested to do this issue Asap !

**Comment by vinzvinci** [comment]
Yeah sure @PatilHarshh. Assigned ✅
