### ISSUE TITLE
[OTHER] Update discord link

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#270]
### What would you like to share?

New discord link: 
https://discord.webxdao.xyz/

### Additional information

We are using different link to our main website, feel free to change it now using the above link ☝️ 

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khushbumaheshwarii** [comment]
Assign me

**Comment by vinzvinci** [comment]
All good @khushbumaheshwarii!

**Comment by khushbumaheshwarii** [comment]
> All good @khushbumaheshwarii!

i made a PR please marged it.

**Comment by khushbumaheshwarii** [comment]
> All good @khushbumaheshwarii!

i made a PR please merge it.
