### ISSUE TITLE
[BUG] Image on about us page does not load

### ISSUE THREAD

**Issue by thehashmap** [WebXDAO/WebXDAO.github.io#273]
### Description of the bug

Also, reloading the about us page gives a 404 error.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/76116523/236334869-55ae6a68-83c7-4dba-85b7-a362a02a2b3a.png)

![image](https://user-images.githubusercontent.com/76116523/236335127-32880b73-8420-4bbd-9f52-ed689650930d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hello, well spotted! The path of the image in [AboutSection ](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/src/components/Home/AboutSection.js#L3) component should be `/public/images/shapes/12.png` 

Do you want to work on it?

**Comment by thehashmap** [comment]
> Hello, well spotted! The path of the image in [AboutSection ](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/src/components/Home/AboutSection.js#L3) component should be `/public/images/shapes/12.png`
> 
> Do you want to work on it?

Yes, I would like to work on it.
