### ISSUE TITLE
[FEATURE] Bump next.js from 12 to 13

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#275]
### Detailed description

Actually, our website uses next.js version 12. However, next.js 13 has been released, offering many new features that could enhance our app's and DX.

### Context

Let's have fun with [appDir](https://nextjs.org/docs/app/building-your-application/routing/defining-routes) 😁

### Possible implementation

Let's use [@shadcn next-template](https://github.com/shadcn/next-template) to get a clean base.

### Additional information

We need to migrate from javascript to typescript.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gptkrsh** [comment]
Should mark it as good-first-issue because just have to clone template?

**Comment by mkubdev** [comment]
I close: https://github.com/WebXDAO/WebXDAO.github.io/commit/d2c77fbb92749c4ebdeeb3b55848b91f6aeac226
