### ISSUE TITLE
[IMPROVEMENT] Add links to the socials section

### ISSUE THREAD

**Issue by gekkowrld** [WebXDAO/WebXDAO.github.io#276]
### Detailed description

In the website when you scroll to the socials section (at the bottom) and click on any of the "links" it takes you to the top of the page.

### Context

It can be confusing for a person who wants a quick access to the socials. So adding the links can be beneficial for such people.

### Possible implementation

Add the links

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prasarCodes** [comment]
Can I work on this?

**Comment by gptkrsh** [comment]
Sorry @prasarCodes, The design of the website is being updated, Thank you for the issue @gekkowrld, pushing this to the team for it to be added to the new design, till then on hold.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by vinzvinci** [comment]
It looks like the issue is related to the old website design. Please create a new issue for the updated design.
