### ISSUE TITLE
[UI]: Reveal image on mouseMove (using js/css or threejs?) ?

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#277]
https://user-images.githubusercontent.com/50140834/238128440-bc0e7388-7763-467e-85bc-a75b02142994.mp4

**Comment by gptkrsh** [comment]
The bg image? We don't need 3js for it, it is almost transparent if the bg of the site is white is already invisible we just have to make the z-index of it lower than of the image

**Comment by mkubdev** [comment]
> The bg image? We don't need 3js for it, it is almost transparent if the bg of the site is white is already invisible we just have to make the z-index of it lower than of the image

Ok then :smile: I was wondering how deeper we wanted to do the animation.
