### ISSUE TITLE
[UI] Integrate custom typographies from the prototype into the UI?

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#278]
![Image](https://github.com/WebXDAO/WebXDAO.github.io/assets/50140834/6f41f995-a906-4ceb-95b0-0b86fd5ca3c1)

**Comment by gptkrsh** [comment]
We can download it as svg from figma and then add it to side, alt text can be the text itself

**Comment by AniketNS** [comment]
Hey I'd like to work on this issue. Assign this to me @gptkrsh

**Comment by vinzvinci** [comment]
anyone, want to work in this under gssoc23?

**Comment by akhilender-bongirwar** [comment]
@vinzvinci, could you please elaborate on what the issue is and what work should be done?

**Comment by praharshaAdhikari** [comment]
Hey! I have experience with tailwind css and nextjs. I can integrate the font from the prototype if you assign this issue to me. [GSSoC23]

**Comment by vinzvinci** [comment]
> Hey! I have experience with tailwind css and nextjs. I can integrate the font from the prototype if you assign this issue to me. [GSSoC23]

Assigned ✅ Looking forward to your contribution!
