### ISSUE TITLE
[FEATURE]improve the blog page

### ISSUE THREAD

**Issue by karthiknadar1204** [WebXDAO/WebXDAO.github.io#283]
### Detailed description

There is excessive animation on the blog page and the cards not not taking up the appropriate space

### Context

The excessive hover animation is not looking good at all and tha cards should be aligned at the center of the page to the left ,it would improve the ui of the page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by mkubdev** [comment]
Hello @karthiknadar1204 👋🏻 
Yes, merge of old code and new aren't clean at all. Do you want to work on it?

Sorry @syedawanya18 will ask @karthiknadar1204 and assign you if no response. :) Thanks for your consideration.

**Comment by karthiknadar1204** [comment]
Would love to work on it @mkubdev

**Comment by mkubdev** [comment]
Cool! I assigned it to you :) 🚀

**Comment by karthiknadar1204** [comment]
@mkubdev Will have to create a separate route for the blog page, you have anything specific in mind that you want me to implement or can i design the page in my own way?

**Comment by vinzvinci** [comment]
> @mkubdev Will have to create a separate route for the blog page, you have anything specific in mind that you want me to implement or can i design the page in my own way?

you can follow our [figma v3 design](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0-1&t=IrCwmNjw3KAyknaI-0)

**Comment by karthiknadar1204** [comment]
Also please add the gssoc label for reference, just a suggestion @vinzvinci

**Comment by karthiknadar1204** [comment]
EXAMS ARE OVER, WILL SUBMIT PR BY WEEKEND
THANK YOU

**Comment by Anmol-Baranwal** [comment]
@karthiknadar1204 
Are you interested in contributing?
If not, please let me know so that I can close the issue.

**Comment by karthiknadar1204** [comment]
I had opened this during gssoc'23,will contribute to this.

Thank you

**Comment by Anmol-Baranwal** [comment]
Sure, thanks for letting me know.
