### ISSUE TITLE
feat: Add Toggle Theme Functionality 

### ISSUE THREAD

**Issue by Saurav-Pant** [WebXDAO/WebXDAO.github.io#285]
### Detailed description

As a user, I want to be able to switch between light and dark themes on the website/app, so that I can choose the one that is easier on my eyes or fits my preferences.

To implement this feature, we will need to add a button or switch somewhere on the page that the user can click or tap to toggle the theme. When the user switches the theme, we will need to update the CSS styles accordingly to apply the appropriate colors, fonts, and other design elements.

In addition, we should consider storing the user's preference for the theme in a cookie or local storage, so that it persists across page reloads and sessions.

By adding this functionality, we can improve the user experience and make the website/app more accessible and customizable for our users.

I think there should we add this
![webXdao](https://github.com/WebXDAO/WebXDAO.github.io/assets/103263909/a3a6db93-eaeb-44ae-a235-10d9f0784f86)

### Context

For Better UX 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Hi, we are not continuing the old website design, please check this issue https://github.com/WebXDAO/WebXDAO.github.io/issues/286 for the info.

**Comment by Saurav-Pant** [comment]
> Hi, we are not continuing the old website design, please check this issue #286 for the info.

okay , plz check #287

**Comment by harshsingh32** [comment]
I would like work on this issue, please assign this issue to me under GSSoC'23.

**Comment by vinzvinci** [comment]
this was added by darkterminal https://github.com/WebXDAO/WebXDAO.github.io/commit/08500f8b6a5a0188a256f0f43462499da46f3ae3, there's a lot more to contribute!
