### ISSUE TITLE
 [GSSoC'23 Contributors] Work on v3 rebranding website 

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#286]
### Detailed description

Hey folks :wave: 

We are rebranding our website to [v3 website design](https://github.com/orgs/WebXDAO/projects/9). Please check the pinned post there.

- If you recently created issue, please close it and create new issue to solve our issue to the new design.
- Check current issues, avoid duplicate issues

### Context

This is really important for us to follow our new brand design created by our design team @WebXDAO/webx-guild-designers.

### Possible implementation

- Follow our [README](https://github.com/WebXDAO/WebXDAO.github.io#readme) for the steps
- Follow our [Contributing guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md#girlscript-summer-of-code23-guidelines-)
- Please use next.js and tailwind

### Additional information

Join our discord if you have doubts: https://discord.webxdao.xyz/

Our @WebXDAO/gssoc-mentors & @WebXDAO/webx-guild-developer will assist you :crossed_fingers: 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
By the way, the hero section has started
https://github.com/WebXDAO/WebXDAO.github.io/pull/280 but still need some improvement. Check my comment on that PR.

**Comment by siddhantsingh186** [comment]
Hey!! Can I work on the remaining sections of the home page? I will pick up the remaining sections since someone is working on the hero section.

**Comment by darkterminal** [comment]
Hi Punk! You can work in the same section btw, and make PR in v3 branch with your feature branch. But, if you want to work with the remaining sections go ahead. Make an issue following what you want to do, after your work is done, then pull a trigger and shoot to the v3 branch! 💥 (PR). 😄

**Comment by siddhantsingh186** [comment]
> Hi Punk! You can work in the same section btw, and make PR in v3 branch with your feature branch. But, if you want to work with the remaining sections go ahead. Make an issue following what you want to do, after your work is done, then pull a trigger and shoot to the v3 branch! 💥 (PR). 😄

Aye Aye Captain!

**Comment by vinzvinci** [comment]
Hey folks, let's wait for the final list of mentor for WebX DAO. I think the GSSOC Program Manager will announce it soon!

We are not going to merge the PR for now, so stay tune.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23

**Comment by Shaurya10101** [comment]
The links in the footer section doesn't seem to work properly in the current website (not in V3) . So is that an issue right now? or the footer needs to be made for the V3 one?

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by vinzvinci** [comment]
Hey everyone, thanks a lot for coming here.

There's a lot to contribute (many features are missing including docs, GitHub actions, etc.. We will check the issues/pr tonight.

Happy Sunday everyone 🙌❤️‍🔥

**Comment by vinzvinci** [comment]
Our GSSoC'23 mentor for this repo:

@Mustafiz04
@siddhi-244

They are going to help us in reviewing your issues and PR 🎉

**Comment by vinzvinci** [comment]
Contributing Guidelines

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/a51a7918-ff33-4dc4-a94b-fac6c5498018)

or check [here](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md#girlscript-summer-of-code23-guidelines-)

**Comment by vinzvinci** [comment]
If you are interested in joining future events like Hacktoberfest or any other open source event, please request to join here: https://github.com/orgs/WebXDAO/teams/open-source-events. This will notify you about upcoming events.

**Comment by vinzvinci** [comment]
Hey folks, we are moving to main branch now. Merged the v3 to main branch.

**Comment by s2sharpit** [comment]
"Hey @vinzvinci @siddhi-244 @darkterminal,

I wanted to inform you that the deployment for the main branch has been halted since the merge of the v3 branch into the main branch. As a result, the main website [webxdao.xyz](https://webxdao.xyz/) is currently inaccessible. Could you please look into this and address the issue?

धन्यवाद

**Comment by vinzvinci** [comment]
> I wanted to inform you that the deployment for the main branch has been halted since the merge of the v3 branch into the main branch. As a result, the main website [webxdao.xyz](https://webxdao.xyz/) is currently inaccessible. Could you please look into this and address the issue?

Thanks for the report. This was the cause of the failure of deployment [(link)](https://github.com/WebXDAO/WebXDAO.github.io/actions/runs/5041842248/jobs/9041899294) @s2sharpit, you can raise an issue about it if you want to get more 🟩 


I'll look at it later when I get back home, but if there's available @WebXDAO/webx-guild-developer they can solve this issue.

**Comment by s2sharpit** [comment]
Hey @vinzvinci @darkterminal @siddhi-244 

The website is not live after merging #309 pr.
And I found it that the `export` script is missing from the package.json file.

Please check this comment: https://github.com/WebXDAO/WebXDAO.github.io/issues/308#issuecomment-1557206090

**Comment by vinzvinci** [comment]
Feel free to add the missing script @s2sharpit

**Comment by Vidip-Ghosh** [comment]
Hi
I want to work on this project. If there is any issue, please assign

**Comment by KamalSritha-04** [comment]
Is this issue still open , can I get it assigned under GSSOC'23?
