### ISSUE TITLE
Folder name to "projcts" to "projects" make issue heading and description

### ISSUE THREAD

**Issue by Saurav-Pant** [WebXDAO/WebXDAO.github.io#287]
There is a discrepancy in the project folder name, currently labeled as  "projcts" instead of "projects".

(https://github.com/WebXDAO/WebXDAO.github.io/assets/103263909/67f54fc1-6bb8-422c-88a6-2b9008495cfd)

assign it to me

**Comment by Saurav-Pant** [comment]
plz add a label for GSSOC'23

**Comment by vinzvinci** [comment]
Thank you!
