### ISSUE TITLE
[FEATURE] add headline, blurbs, partners and footer sections to the homepage

### ISSUE THREAD

**Issue by siddhantsingh186** [WebXDAO/WebXDAO.github.io#289]
### Detailed description

- [x] Add the headline, blurbs, and partners section on landing page as per the v3 Figma design.
- [ ] Improve the footer section.

### Context

Would be a new feature on the community website.

**Comment by siddhantsingh186** [comment]
I would like to work on this issue.

**Comment by darkterminal** [comment]
Yup! Go ahead and have fun Punk! Don't forget to 🕺 while 👨‍💻 🤣

**Comment by MAYANKpandey14** [comment]
Hey everyone @darkterminal @siddhantsingh186 @vinzvinci.

**Comment by MAYANKpandey14** [comment]
@siddhantsingh186. Can we collaborate on this together, you can build all the remaining sections except the footer section. It will be a good opportunity for me to collaborate and learn.

**Comment by siddhantsingh186** [comment]
#298

**Comment by siddhantsingh186** [comment]
#298 Implemented my changes in this PR. Can you review @darkterminal @vinzvinci

**Comment by siddhantsingh186** [comment]
> @siddhantsingh186. Can we collaborate on this together, you can build all the remaining sections except the footer section. It will be a good opportunity for me to collaborate and learn.

Okay! no problem. Can you check with @darkterminal @vinzvinci whether they approve?

**Comment by s2sharpit** [comment]
Hi everyone,

I'm excited to contribute to GSSOC. I would be extremely grateful if I could collaborate with you, @siddhantsingh186, on this particular issue. I'm really interested in working on the blurbs section. Would it be possible for us to collaborate on this together?

धन्यवाद

**Comment by MAYANKpandey14** [comment]
> > @siddhantsingh186. Can we collaborate on this together, you can build all the remaining sections except the footer section. It will be a good opportunity for me to collaborate and learn.
> 
> Okay! no problem. Can you check with @darkterminal @vinzvinci whether they approve?

Yeah sure. @vinzvinci @darkterminal  If you allow should is start working with footer section

**Comment by MAYANKpandey14** [comment]
Is this looking fine.Only problem is i am not sure whether to use icons for social or simple text similar to old website. Also I would suggest to use react icons to be more consistent in terms of icons across the website.@darkterminal @siddhantsingh186 @vinzvinci 

![Screenshot from 2023-05-22 00-02-26](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/045e67dd-dcb4-4f62-9e90-f9c676a7b909)
This one is of xl devices .

![Screenshot from 2023-05-22 00-06-15](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/6b6061de-1c1b-4cfe-9902-d4051dcccbe6)
![Screenshot from 2023-05-22 00-06-49](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/e8054b15-9c91-4976-a14d-3da93c92c62d)
![Screenshot from 2023-05-22 00-07-08](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/8f66c691-f040-4530-8ae6-cf6b303d4f6d)

**Comment by vinzvinci** [comment]
Looks good @MAYANKpandey14, please create PR for this.

**Comment by darkterminal** [comment]
@MAYANKpandey14 That looks good and amazing! :fire: please create PR for this.

**Comment by Anmol-Baranwal** [comment]
I'm closing this, since the PR is merged.

Please feel free to reopen it if I'm wrong, or you'd like to contribute and have further discussions.
