### ISSUE TITLE
[BUG] Update the PR template link

### ISSUE THREAD

**Issue by thehashmap** [WebXDAO/WebXDAO.github.io#290]
### Description of the bug

The current pull request template link (https://github.com/WebXDAO/WebXDAO.github.io/blob/main/.github/pull_request_template.md) in CONTRIBUTING.md leads to a page not found error. 
It needs to be updated to: https://github.com/WebXDAO/WebXDAO.github.io/blob/main/.github/PULL_REQUEST_TEMPLATE.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Great catch, thanks! Would you like to work on this? 🙂

**Comment by vinzvinci** [comment]
@sarthkdobriyal, you merged on your own fork.

**Comment by mkubdev** [comment]
Hey @sarthkdobriyal, you merged your PR in your own fork. Do you need help ?
