### ISSUE TITLE
Blurbs component

### ISSUE THREAD

**Issue by 7twik** [WebXDAO/WebXDAO.github.io#291]
### Detailed description

I would like to work on the blurbs component of v3 rebranding of  WebXDAO as a part of @GSSOC'23.. @vinzvinci 

### Context

This change was asked in the suggestions

### Possible implementation

will be designing the exact same design as given

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darkterminal** [comment]
Thank you for join with us!
what feature you will be adding, please give the proper title 😄

**Comment by darkterminal** [comment]
@7twik add a detail section that you want to contribute please, and read our [CONTRIBUTING GUIDELINE](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by mkubdev** [comment]
I close since #366 fix it!
