### ISSUE TITLE
[FEATURE] Change Contributors Container to fit website Navbar width (better UI/UX) [GSSOC'23]

### ISSUE THREAD

**Issue by vishnu9865** [WebXDAO/WebXDAO.github.io#293]
## Change Contributor Container width to fit Navbar width
- Change the max width of the Contributors Container (having many blog cards).
- Helps the content better fit in with the website.

### Context

# Why the Change ?
 - Compare both images.

| Projects page | Contributors Page |
|---|----|
| ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/227eec7e-2bc6-4ea7-af39-79150b6806f6) |  ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/a3ef0c72-9847-43ec-a1f0-75dab9a02ea3) |
 - Both are equally good card wise but due to container width of the contributor page. It feels out of place and has bad UX.

### Would you like to work on this issue?

 - [X] Yes, I want to work on this issue!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vishnu9865** [comment]
Hi @vinzvinci,
 - I would like to contribute for the above mentioned improvement.
 - Please assign this issue to me.
 - Thanks in Advance.
Regards,
Jeyavishnu S

**Comment by darkterminal** [comment]
Yooo welcome to WebXDAO! tada
Please do not forget to read our Contribution Guideline and README.

**Comment by vishnu9865** [comment]
@vinzvinci Sir, Is there any changes to the already made PR ? If so I will gladly change it. Thank you
