### ISSUE TITLE
Dark theme option (V3 is brighter theme)

### ISSUE THREAD

**Issue by Shaurya10101** [WebXDAO/WebXDAO.github.io#294]
### Detailed description

The V3 website design has a lighter theme , a lot of developers prefer dark theme . We can merge the existing design with the new design as a switch for dark mode and light mode with information(About section) of the light mode to be on the dark mode as well 

### Context

This would make the website more appealing 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lalitkumawat1m** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by vinzvinci** [comment]
Already existing https://github.com/WebXDAO/WebXDAO.github.io/pull/280. 

There's a lot more to improve, check the current codebase on your local.
