### ISSUE TITLE
[FEATURE] : Add System default setting for Dark/Light modes

### ISSUE THREAD

**Issue by dev-AshishRanjan** [WebXDAO/WebXDAO.github.io#296]
### Detailed description

This website is in Dark mode only.
so I want to create a light theme following the color scheme of the current theme.
And wanted to create a Theme Toggle button.

Can you assign this issue to me under GSSoC'23. so, I can start working on this issue

### Context

This is important because some people like websites in light mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Light mode and dark mode is existing now.

**Comment by dev-AshishRanjan** [comment]
I was talking about Light mode and Dark mode,
But also with system default.
It can be done in css code.

you can find this design in my portfolio - http://krashish.live/

The concept is : 
- If the system is in dark mode : Dark mode gets activated 
- If the system is in light mode : Light Mode gets activated
This happens without clicking the mode toggle button
And system (default) is chosen by default.

**Comment by dev-AshishRanjan** [comment]
> Yeah, good idea 💯 maybe change the issue title for it?

Title has been changed to ***[FEATURE] : Add System default setting for Dark/Light modes***

Now if you can assign me this issue , then I can start working on it.

**Comment by darkterminal** [comment]
Toggle button it's ok... like common website do.

**Comment by darkterminal** [comment]
Yup! something like that... `option2` is more common and familiar

**Comment by darkterminal** [comment]
So it's done?!

**Comment by mkubdev** [comment]
> So it's done?!

Yes... 👀

**Comment by dev-AshishRanjan** [comment]
> Hi everyone 👋🏻
> 
> Very nice collaboration there 💡 But the app use [`next-theme`](https://github.com/pacocoursey/next-themes) as theme provider and the lib already have built-in System setting with prefers-color-scheme... + theme switcher is already there.

Hi @mkubdev ,
But as per the built-in system settings of next-theme, *the feature doesn't work properly*.

When you are in light mode, and click theme toggle button, the value of mode changes from `system` to `light` , according to usetheme()

**So, it may work in dark mode , but if your system is in light mode you have to click twice on theme toggle button to go to dark mode for the first time**.

This issue is fixed on my PR, you can check the Preview Deployment.
You can find the difference after checking both the Preview (the preview deployed for my PR) and Production Deployment
