### ISSUE TITLE
feat: Add active page indicator in Navbar [GSSoC'23]

### ISSUE THREAD

**Issue by mani200307** [WebXDAO/WebXDAO.github.io#297]
### Description of the bug

We could add a functionality to the website to show the active page by highlighting the menu item in the navbar.

We could highlight the active page in the navbar.

Could you please assign me this issue under GSSoC'23?

### Please add screenshots (if applicable)

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/89850065/bfadc7a2-694d-4789-ad82-0279013fb106)

The active page could be highlighted by giving an active page color (like Blue color)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mani200307** [comment]
Could you please assign me this issue under GSSoC'23? Can I work on this issue?

**Comment by darkterminal** [comment]
Yup! And check [this](https://github.com/WebXDAO/WebXDAO.github.io/issues/299#issuecomment-1556506387) issue comment first, before you work with this issue.

**Comment by mani200307** [comment]
So, @darkterminal, I should work on this issue after the version changes is complete. Because, directory changes may occur due to app/ directory to be included.

**Comment by darkterminal** [comment]
You can work on this issue and push it to the `main` branch.

**Comment by s2sharpit** [comment]
Hey, Can I work on this issue?

**Comment by s2sharpit** [comment]
> @s2sharpit @mani200307 Are you interested in contributing? If not, please let me know so that I can close the issue.

Yaa, I'm interested in contributing to this issue. I will raise PR soon.

**Comment by Anmol-Baranwal** [comment]
> > @s2sharpit @mani200307 Are you interested in contributing? If not, please let me know so that I can close the issue.
> 
> Yaa, I'm interested in contributing to this issue. Can u assign me the issue. I will raise PR then.

Done :)
