### ISSUE TITLE
To Update Next.js Version to Stable Release for App Directory [v3]

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#299]
Dear @darkterminal @vinzvinci 

I hope this message finds you well. I would like to bring to your attention an important matter regarding the Next.js version being used in the project. Currently, the project is relying on an outdated version of Next.js, which still includes the beta release of the app directory. It is crucial to update the Next.js version to a more recent release, specifically [Next.js 13.4](https://nextjs.org/blog/next-13-4), where the `/app` router has been `stabilized`.

By `updating` the Next.js version, we can leverage the `benefits of the latest stable release` and ensure optimal performance, security, and compatibility with the evolving ecosystem. Furthermore, keeping the project up-to-date with the latest framework version will provide us with access to new features, improvements, and bug fixes.

I would be more than willing to take up the `responsibility of updating the Next.js version` of the project. As an experienced developer, I understand the `significance of this task` and can ensure a `smooth transition` by carefully addressing any potential compatibility issues and thoroughly testing the codebase. I am confident that this update will contribute to the overall stability and longevity of the project.

If you find my proposal acceptable, I kindly request that you consider `assigning` this task to me. I will promptly initiate the process and diligently follow the best practices for version control to ensure a seamless integration of the new Next.js release.

Thank you for your attention to this matter. I look forward to your response and the opportunity to contribute to the improvement of this project.

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).

**Comment by Tushar98644** [comment]
I would like to take up the issue under GSSoC'23

**Comment by s2sharpit** [comment]
Hey @Mustafiz04 @siddhi-244 
Can you please assign me this issue under GSSOC 23...

**Comment by vinzvinci** [comment]
we are using main branch now, please check there!

**Comment by darkterminal** [comment]
@s2sharpit You need to check the `main` branch as @vinzvinci said.

**Comment by s2sharpit** [comment]
Hey, I have created the PR, please review it.
