### ISSUE TITLE
Footer component for the V3 website 

### ISSUE THREAD

**Issue by Shaurya10101** [WebXDAO/WebXDAO.github.io#300]
### Detailed description

Let me design the footer section for the V3 rebranded website under GSSoC'23

### Context

I'll be implementing it as per the design provided

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MAYANKpandey14** [comment]
Hey @Shaurya10101  really appreciate your spirit of contribution and collaboration but kindly read https://github.com/WebXDAO/WebXDAO.github.io/issues/289 as this feature is being discussed there.
Welcome to the community.

**Comment by Shaurya10101** [comment]
Oh Thank you I didn't notice it Sorry!

**Comment by vinzvinci** [comment]
I am closing this because it already exists. Always check current issues. Don't worry there's a lot more to contribute!
