### ISSUE TITLE
[FEATURE] Add Blog Page

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#305]
### Detailed description

- [ ] Implement the Blog Page as per the new design.

### Context

New feature on the community website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @siddhi-244 @darkterminal @vinzvinci 

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by vinzvinci** [comment]
The blog page will be changing to a new design. Please wait for now. I will update you when the new design is complete.

**Comment by s2sharpit** [comment]
Okay, Sure!

**Comment by vinzvinci** [comment]
btw I just noticed, there's past issue #283 currently working on this. You can work on other pages for now.

**Comment by s2sharpit** [comment]
> btw I just noticed, there's past issue #283 currently working on this. You can work on other pages for now.

Thank you for bringing that to my attention. I wasn't aware of the past issue #283 related to this matter. I appreciate your guidance, and I'll redirect my efforts towards working on other pages for now. Please let me know if there are any specific areas you'd like me to focus on. I'm eager to contribute effectively to the project.

**Comment by vinzvinci** [comment]
Yeah sure, there's a lot more to come @s2sharpit! We'll keep you folks updated, just always check our pinned post.

**Comment by KamalSritha-04** [comment]
Is this issue still open, if it is can I please get assigned to this under GSSOC'23?

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
As there is no pr from the issue #283 .
Can I work on this.
If yes, can you assign me this issue.

**Comment by Anmol-Baranwal** [comment]
> Hey @vinzvinci @siddhi-244 @mkubdev @Panquesito7 @Mustafiz04 @Anmol-Baranwal @darkterminal As there is no pr from the issue #283 . Can I work on this. If yes, can you assign me this issue.

Don't tag everyone. You can tag me or `@vinzvinci`.

Also, I am not aware about any blog design, can you share that link, where v3 blog design is shown.

**Comment by s2sharpit** [comment]
> Don't tag everyone. You can tag me or `@vinzvinci`.
> 
> Also, I am not aware about any blog design, can you share that link, where v3 blog design is shown.

Hey @Anmol-Baranwal 
It's in the [figma design](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0)

**Comment by Anmol-Baranwal** [comment]
Okay, then others will assign you the work, if the design is completed.

**Comment by Kushagra102** [comment]
Hey @vinzvinci I have viewed the design of the blog page and would like to work on this issue.

**Comment by Anmol-Baranwal** [comment]
@Kushagra102 
Since `s2sharpit` asked for it first, I am assigning the task to him. Please search for other issues to contribute to. If you have any ideas, feel free to suggest them in an issue, and we will guide you on what you can contribute.

**Comment by Anmol-Baranwal** [comment]
@s2sharpit 
I don't have any information regarding the finalization of this design, so I cannot guarantee that the pull request will be merged. Let me ask the same question in the Discord channel.

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
What's your views on it?

**Comment by Anmol-Baranwal** [comment]
@s2sharpit 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by vinzvinci** [comment]
You can work on this now @s2sharpit

**Comment by s2sharpit** [comment]
Subject: Inquiry about Data Source & Social Media Profile Links for Cards

Dear @vinzvinci @Anmol-Baranwal ,

I am writing to inquire about the data source and social media profile links for the cards in the API. Could you kindly clarify if the card data and associated GitHub, LinkedIn, and Twitter profile links are automatically sourced from an API or if they need to be added manually?

If the data, including social media links, is obtained from an external API, please provide documentation or guidelines for accessing it.

Alternatively, if the data and links are to be added manually, please advise on the recommended method. Could you kindly provide instructions on how to add the GitHub, LinkedIn, and Twitter profile links to the cards? It would be helpful to understand the specific format or structure required for successful integration.

I greatly appreciate your assistance and prompt response.

धन्यवाद (Thank You)

**Comment by Anmol-Baranwal** [comment]
> Subject: Inquiry about Data Source & Social Media Profile Links for Cards in Blog Page.
> 
> Dear @vinzvinci @Anmol-Baranwal ,
> 
> I am writing to inquire about the data source and social media profile links for the cards in the API. Could you kindly clarify if the card data and associated GitHub, LinkedIn, and Twitter profile links are automatically sourced from an API or if they need to be added manually?
> 
> If the data, including social media links, is obtained from an external API, please provide documentation or guidelines for accessing it.
> 
> Alternatively, if the data and links are to be added manually, please advise on the recommended method. Could you kindly provide instructions on how to add the GitHub, LinkedIn, and Twitter profile links to the cards? It would be helpful to understand the specific format or structure required for successful integration.
> 
> I greatly appreciate your assistance and prompt response.
> 
> धन्यवाद (Thank You)
> 
> Please refer to the provided screenshot for reference: ![image](https://user-images.githubusercontent.com/104740281/252654508-9be567f2-71a3-446e-8ac0-97873cc03a7c.png)
> 
> Figma Link: https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=1330%3A2186&mode=design&t=UZviNxVkeeugCtFV-1

As per my knowledge, you cannot retrieve social links from GitHub api, so you need to add it manually. Just leave it empty for now. We will ask you to add the links before merging PR.
