### ISSUE TITLE
[BUG] Github and Twitter link on navbar redirects to unknown's profile.

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#306]
### Description of the bug

The github and twitter links on navbar redirects to unknown's profile.

### Please add screenshots (if applicable)

https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/34801247-9aa8-481e-8068-02ea5b0045c9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @siddhi-244 @darkterminal @vinzvinci

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by darkterminal** [comment]
Ouch! Nice catch punk... I forgot to add our Social Links :stuck_out_tongue_winking_eye: . OhMyPunk! That embarrassing :roll_eyes:

**Comment by vinzvinci** [comment]
here's the twitter link: https://twitter.com/WebXDAO
