### ISSUE TITLE
[BUG] Community Partners Section is having irregular containers width.

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#307]
### Description of the bug

The Community Partners section on the landing page of the website is having irregular container width.

### Please add screenshots (if applicable)

![](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/c236d686-cf6c-4f14-a9e9-8f25d9dc3caa)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @siddhi-244 @darkterminal @vinzvinci

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by vinzvinci** [comment]
Great catch! Assigned ✅

**Comment by darkterminal** [comment]
Wooo... nice drive :car:
