### ISSUE TITLE
[BUG] Social Media links not woking

### ISSUE THREAD

**Issue by parthpathakpp1** [WebXDAO/WebXDAO.github.io#311]
### Description of the bug

When we click on the twitter and discord logo it does not direct us to any link . 

### Please add screenshots (if applicable)

![webxdaoissue3](https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/49209911-410d-4538-9c43-1ca878be85fb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
you can use https://discord.webxdao.xyz/ & https://twitter.com/WebXDAO

**Comment by parthpathakpp1** [comment]
> you can use https://discord.webxdao.xyz/ & https://twitter.com/WebXDAO

can you please give me GSSOC'23 label?
