### ISSUE TITLE
[FEATURE] Hover Effect on Community Partners Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [WebXDAO/WebXDAO.github.io#312]
### Detailed description

When we hover on Community Partners Section cards it does not show any hovering effect which looks very static . 

https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/246c6760-720a-404d-9ff6-6de45b4917f8

### Context

This change is important to me because it will help me showcase my skills to other people . 

### Possible implementation

I will add some cool animations and hovering effect on cards . Which will have box-shadow on hovering and many things. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthpathakpp1** [comment]
assign me this issue under GSSOC'23.

**Comment by vinzvinci** [comment]
You can follow [the hover effect](https://www.figma.com/proto/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=190-3830&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=190%3A3830) here, it should be on button only. 

You can check our [v3 roadmap](https://github.com/orgs/WebXDAO/projects/9?pane=issue&itemId=28110723)

**Comment by parthpathakpp1** [comment]
> You can follow [the hover effect](https://www.figma.com/proto/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=190-3830&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=190%3A3830) here, it should be on button only.
> 
> You can check our [v3 roadmap](https://github.com/orgs/WebXDAO/projects/9?pane=issue&itemId=28110723)

ok

**Comment by darkterminal** [comment]
Also, fix the cover image size if you can...

**Comment by vinzvinci** [comment]
Already fix the image size here https://github.com/WebXDAO/WebXDAO.github.io/pull/324
- You can work on hover effect

**Comment by parthpathakpp1** [comment]
> Already fix the image size here #324
> 
> * You can work on hover effect

ok working on it.

**Comment by vinzvinci** [comment]
don't forget to git pull and fetch, I did merged the pr now

**Comment by parthpathakpp1** [comment]
> don't forget to git pull and fetch, I did merged the pr now

ok , BTW is it possible to tell me the color code . Been trying to find out but could not .

**Comment by vinzvinci** [comment]
> ok , BTW is it possible to tell me the color code . Been trying to find out but could not .

here #411AFF

**Comment by parthpathakpp1** [comment]
> > ok , BTW is it possible to tell me the color code . Been trying to find out but could not .
> 
> here #411AFF

thanks <3
