### ISSUE TITLE
[FEATURE] Add Favicon to the website

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#314]
### Detailed description

The latest v3 of the website does not have the favicon.

### Context

It's important to recognize the website.

### Possible implementation

Adding this as the favicon:

![JuiW8VLh_400x400](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/cb59d9d3-4367-406f-93ac-275ddbc43bca)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @vinzvinci @siddhi-244 @darkterminal

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by vinzvinci** [comment]
I think transparent is better? 
![WebX Dao WXD logo](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/c93c7291-0769-45ed-8058-0a49bf225957)

**Comment by s2sharpit** [comment]
Ok Sure, I will add it as favicon. 😊

**Comment by s2sharpit** [comment]
Hey @vinzvinci @darkterminal @siddhi-244 

Which one of them looks better,

TRANSPARENT

![Screenshot (412)](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/29b1b0d1-b4b5-43ae-a276-4725587aaa06)

![Screenshot (413)](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/15aa0db2-9101-418b-ab11-ca40377b4470)

OR THIS

![Screenshot (414)](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/7e9b0429-d141-4b70-bd0e-0072647cdcf5)

![Screenshot (415)](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/c3e99b20-3685-4cbf-a0c4-7323ad396c03)
