### ISSUE TITLE
[ENHANCEMENT] description Card is not responsive across different screen sizes

### ISSUE THREAD

**Issue by Preetam078** [WebXDAO/WebXDAO.github.io#320]
### Description of the bug

I observed that the description card below the welcome page is not responsive at least at medium screen size too.

### Please add screenshots (if applicable)

![Screenshot from 2023-05-22 21-12-59](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/839257d2-a10a-45f4-a450-e57721d1a045)

### Add any other context about the problem here

I would like to make the card more responsive. Please assign this task to me under GSSoC 2023

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Preetam078** [comment]
hii admin please assign this task to me under the GSSoC "23

**Comment by vinzvinci** [comment]
This already fixed, but can you fix this?
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/2e4d9554-acd0-4a78-a492-8f524736784c)
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/787b672f-d296-4480-b3e4-cc7bcbf7bccf)

or

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/74454cc2-b7d5-446d-b01c-f0b82838e627)

**Comment by knight-95** [comment]
> This already fixed, but can you fix this? ![image](https://user-images.githubusercontent.com/73097560/240128792-2e4d9554-acd0-4a78-a492-8f524736784c.png) ![image](https://user-images.githubusercontent.com/73097560/240128860-787b672f-d296-4480-b3e4-cc7bcbf7bccf.png)
> 
> or
> 
> ![image](https://user-images.githubusercontent.com/73097560/240128965-74454cc2-b7d5-446d-b01c-f0b82838e627.png)

Can you please elaborate this issue

**Comment by mkubdev** [comment]
Hi everyone :wave: 
I created a new issue: #333 to elaborate more about what @vinzvinci shared. I'm closing this, follow up on #333 :)
