### ISSUE TITLE
[FEATURE]Adding the WebXTeam page

### ISSUE THREAD

**Issue by Vaani-pathariya** [WebXDAO/WebXDAO.github.io#321]
### Detailed description

I would like to work on the webXteam page on the light theme according to the new design . Thus I would want this issues to be assigned to me under Gssoc tab !

### Context

Adding the team page instead of the 404 page 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mustafiz04** [comment]
sure @Vaani-pathariya.
Assigning it to you.

**Comment by Mustafiz04** [comment]
This is figma link for your reference
https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0%3A1&t=sIgkclXzhKJ01axk-1

**Comment by vinzvinci** [comment]
Any updates on this? 

You can implement this page: 
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/e5da87ed-94f7-4dcc-8eae-d5af8b8e2591)

**Comment by Vaani-pathariya** [comment]
Yes I am working of it, had college exams because of which it got a bit delayed , but it is in progress.

**Comment by Vaani-pathariya** [comment]
> Any updates on this?
> 
> You can implement this page: ![image](https://user-images.githubusercontent.com/73097560/241710490-e5da87ed-94f7-4dcc-8eae-d5af8b8e2591.png)

ok
