### ISSUE TITLE
[FEATURE] Add Contributors Page [GSSoC'23]

### ISSUE THREAD

**Issue by vishnu9865** [WebXDAO/WebXDAO.github.io#323]
### Detailed description

 - I would like to work on implementing the Contributors Page in the new Rebranding of the Website under GSSoC'23.

### Context

 - A working contributor page instead of 404 page.
 - I would like to create the page for both light and dark themes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mustafiz04** [comment]
Sure @vishnu9865 
Assigning it to you.

**Comment by Mustafiz04** [comment]
This is the Figma link for your reference. Make sure the page should like this.
https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0%3A1&t=sIgkclXzhKJ01axk-1

**Comment by vishnu9865** [comment]
Thank you @Mustafiz04 for assigning me. 👍🏽😊

**Comment by vishnu9865** [comment]
@Mustafiz04 Sir,
 - Just one doubt.
 - couldn't run the project locally with 'npm run dev' due to some errors.
 - tried to resolve them but It requires tampering with config files.
 - Is there anything I would need to do before running this project locally ?
 - I would really appreciate your time for me to resolve this issue.

Thanks in Advance.
regards,
Jeyavishnu @vishnu9865 

The Screenshot:
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/3dd63186-145e-4e79-816b-260be8f7b081)

**Comment by vishnu9865** [comment]
@Mustafiz04 Sir,
 - The above issue is temporarily solved by adding the below code (highlighted green by git) to the 'next.config.mjs' file.
 - I don't know if this issue is for everybody when trying to run locally.
 - I basically disabled the nextjs image optimization api.
 
 Screenshot for Reference:
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/84339027-1f28-4410-90e0-236950eaa87a)

**Comment by Mustafiz04** [comment]
Checking your issues.

**Comment by mkubdev** [comment]
Hi, @Mustafiz04 fixed the issue with https://github.com/WebXDAO/WebXDAO.github.io/pull/334.

Try to sync with the main branch and you should be good to run the project now!

**Comment by Mustafiz04** [comment]
@vishnu9865 your issue has been resolved. Please pull the lastest code for branch v3, then you will continue with your feature.
