### ISSUE TITLE
[FEATURE] Add a scroll to top navigation button

### ISSUE THREAD

**Issue by abhinav-m22** [WebXDAO/WebXDAO.github.io#326]
### Detailed description

There is an absence of a scroll-to-top button on the website. The website's user experience would be improved by the addition of this floating button.
Due to my prior experience in building for personal projects, I'd like to contribute this feature.

Please assign me the task under GSSoC'23.

### Context

The scroll-to-top nav button is a useful component of the web page as it routes the page back to the top on the main page.
As the length of the page increases, it becomes a tedious task to scroll back to top through mouse.

### Additional information

I want to work on this feature.
Please assign me the task under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
check this https://github.com/orgs/WebXDAO/teams/webx-guild-developer https://github.com/orgs/WebXDAO/teams/gssoc-mentors and give feedback

**Comment by abhinav-m22** [comment]
Hey @vinzvinci ..
I didn't get what you are saying. How to check?
I wanted to work on the feature issue.

**Comment by vinzvinci** [comment]
I mentioned the team and other mentors to check this issue if we will continue this early since the landing page is not that long, but I'm waiting for their feedback.

**Comment by darkterminal** [comment]
Hmmm... I need to get some ☕ and think about it.

**Comment by mkubdev** [comment]
Hello @abhinav-m22 ! Thanks for your contribution to our issues. I think adding a scroll-to-top feature is a cool idea. Feel free to implement it ⚡ Do you want to be assigned?

FYI, the app use lucide icon: https://lucide.dev/

**Comment by abhinav-m22** [comment]
@mkubdev Yeah thanks... I'll work on it.
It would be great if you assign to me, or else someone could work on the same feature simultaneously which will an issue.

**Comment by mkubdev** [comment]
Sure I asked you above :) I'll assi you!

**Comment by abhinav-m22** [comment]
@mkubdev 
I have made a PR - #335 
Please have a look
