### ISSUE TITLE
[FEATURE] Applying gradients to heading

### ISSUE THREAD

**Issue by dhrumishah** [WebXDAO/WebXDAO.github.io#329]
### Detailed description

We can apply the gradient in heading of particular section to make it more visually appealing.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/84569241/2d4c9908-f019-4c46-8dd6-fcaea3eaf2e6)

### Context

This change can make the website look more elegant.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darkterminal** [comment]
You need to read this issue first #286 and follow this [design](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0%3A1&t=Kn5tue58tUAwx8nH-1)

**Comment by mkubdev** [comment]
Hi, welcome here :wave:
I think this is a very nice idea instead of using one color, and it will be more elegant. 🔥 Do you want to work on it?

**Comment by dhrumishah** [comment]
> Hi, welcome here 👋 I think this is a very nice idea instead of using one color, and it will be more elegant. 🔥 Do you want to work on it?

Hey! Yes I can work on it.

**Comment by mkubdev** [comment]
I assigned you ⚡

**Comment by Mustafiz04** [comment]
@dhrumishah please follow this design and let me know if you have any issue.

<img width="1043" alt="Screenshot 2023-05-23 at 11 05 38 PM" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/49086821/829051e0-8d5a-474d-b445-a102b9319132">

**Comment by dhrumishah** [comment]
> @dhrumishah please follow this design and let me know if you have any issue.
> 
> <img alt="Screenshot 2023-05-23 at 11 05 38 PM" width="1043" src="https://user-images.githubusercontent.com/49086821/240374141-829051e0-8d5a-474d-b445-a102b9319132.png">

Hey I have made PR. If you need any changes, Do let me know.

**Comment by Anmol-Baranwal** [comment]
Completed with #337
