### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by kedar1998** [WebXDAO/WebXDAO.github.io#331]
### Detailed description

I would like to make whole home page responsive. 

### Context

Most people open websites on mobile. It is bad user experience for website which is not responsive. It would be easy for end user to access website from mobile with hampering user experience.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MAYANKpandey14** [comment]
I agree with @kedar1998 , the whole hero and blurb section is unresponsive.

**Comment by kedar1998** [comment]
Yes!! I would love to work on this

**Comment by Mustafiz04** [comment]
@kedar1998 sure you can work on this issue but please make sure about issue #333.
I am assigning it to you.

**Comment by kedar1998** [comment]
Thank you!!! I will start working on this.

**Comment by Mustafiz04** [comment]
For now, keep it untouched.

**Comment by mkubdev** [comment]
Hello @kedar1998, do you have some update?

**Comment by Soulpurr** [comment]
@Mustafiz04 is this issue still open?

**Comment by Soulpurr** [comment]
@mkubdev can i work on this?

**Comment by kedar1998** [comment]
@mkubdev  I will close it by tomorrow. One more thing #333 is causing screen size issue. Because of that section there is gap on right side of screen in mobile. It would be better if I can work on whole section. What do you think?

**Comment by mkubdev** [comment]
Hello @kedar1998 :wave:

#333 is in review and almost merged (see #366)
Screen size issue was due to the navbar, and pr #371 fixed it!

We think to close this issue. Thank you all for your time. Feel free to open another.
Your cooperation in resolving this matter is greatly appreciated. 🤝
