### ISSUE TITLE
[FEATURE] Responsivness of Blurbs

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#333]
### Detailed description

Blurbs on homepage aren't responsive with screen size: 
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/50140834/bb628cd8-65ce-4f49-a496-aa16c23363fe)

We should add Tailwind utility classes on this section of `app/page.tsx L114`: https://github.com/WebXDAO/WebXDAO.github.io/blob/87ad6dc826b598a23ad97f208c6b986fffc2ca68/app/page.tsx#L114

See more [on the official documentation](https://tailwindcss.com/docs/responsive-design) to learn how Responsive is managed with Tailwind.

### Context

Responsiveness is very important. 💡 Users using more phones than browser!

### Possible implementation

This is a possible implementation, using Tailwind utility classes:

```js
<section className="flex justify-center px-4 md:px-10 lg:px-40 py-0">
  <div className="my-12 flex flex-col md:flex-row gap-8">
    <div className="flex flex-col items-center justify-center gap-3 text-center">
      <div className="border-l-3 flex justify-center rounded-lg border-white bg-white p-8 shadow-md shadow-purple-300">
        <Icons.collaborate className="h-15 w-15 mr-1" />
      </div>
      <div className="text-lg font-bold">Collaborate</div>
      <span className="text-sm">
        Collaborate with other members to achieve common goals and objectives.
      </span>
    </div>

    <div className="flex flex-col items-center justify-center gap-3 text-center">
      <div className="border-l-3 flex justify-center rounded-lg border-white bg-white p-8 shadow-md shadow-purple-300">
        <Icons.blockchain className="h-15 w-15 mr-1" />
      </div>
      <div className="text-lg font-bold">Blockchain</div>
      <span className="text-sm">
        Dedicated to exploring new ways to leverage the power Of this transformative
        technology.
      </span>
    </div>

    <div className="flex flex-col items-center justify-center gap-3 text-center">
      <div className="border-l-3 flex justify-center rounded-lg border-white bg-white p-8 shadow-md shadow-purple-300">
        <Icons.decentralization className="h-15 w-15 mr-1" />
      </div>
      <div className="text-lg font-bold">Decentralization</div>
      <span className="text-sm">
        Operates in a decentralized manner, giving power to its community members.
      </span>
    </div>
  </div>
</section>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Preetam078** [comment]
hi member while I was setting up the local environment, after installing "npm install" and hitting "npm run dev" getting some error 
below 
![Screenshot from 2023-05-24 23-51-19](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/8bc6d452-b472-45df-b48c-b5c24963c870)
and 
![Screenshot from 2023-05-24 23-51-27](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/7202c0bd-55ca-43fb-b74d-2af7ebbef2fd)

**Comment by Preetam078** [comment]
can anyone help me

**Comment by darkterminal** [comment]
Hmmm... what is your nodejs version? Did you try it to remove `node_modules` and run `npm install` again?

**Comment by Preetam078** [comment]
yes i removed cache and **node_modules**  but getting same error can you give a vows of what version of node the developers must use to avoid the error

**Comment by mkubdev** [comment]
> yes i removed cache and **node_modules** but getting same error can you give a vows of what version of node the developers must use to avoid the error
> 
> current node version = 14.21.3 ( in local machine )

Hey, I'm sorry I can't replicate it. Can you try using `node >= 16` ?

**Comment by Preetam078** [comment]
hello admin know the localserver is running after node version has been upgraded to 16. i think in this case we should update the readme.md file to give an addition instruction to use node version 16 or higher for development environment. please assign this task to me as well
