### ISSUE TITLE
[FEATURE] Add a Useful Footer.

### ISSUE THREAD

**Issue by vikashjalandra** [WebXDAO/WebXDAO.github.io#336]
### Detailed description

I want to add a useful footer that will contain some quick links and social media handle links.

### Context

A website is incomplete without a footer. I know that this website is awesome and will be awesome without a footer but if we add a footer, it will enhance its beauty and also the users can have some direct links to the website and social media handles.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MAYANKpandey14** [comment]
Hey @vikashjalandra this feature has been added already kindly read #289. Welcome to the community, really like your collaboration spirit . I hope you will find other issues to contribute .

**Comment by vinzvinci** [comment]
Closing this now. Thanks @MAYANKpandey14 🎉
