### ISSUE TITLE
[FEATURE] Create Updated Navbar based on V3 design files. [GSSOC'23]

### ISSUE THREAD

**Issue by vishnu9865** [WebXDAO/WebXDAO.github.io#341]
### Detailed description

 - Change the Navbar with Updated design according to the V3 rebranding [Figma file](https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&node-id=0-1&t=ksleMxOBsRQ7u0pd-0).
 - But also include the Theme toggler and links from the old design.
 -  And also the Footer section if possible.

### Context

 - I had already contributed to creating the contributors page. Issue #323
 - I was given a figma file to work with.
 - but the navbar commonly throughout the website does not resemble the figma file design.
## Figma Design
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/fb62fce6-80a8-4bbf-a65a-77019418c894)
## Current Design
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/de020f1e-536e-4543-964c-545cc532f1d1)
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishnu9865** [comment]
@Mustafiz04 @vinzvinci @darkterminal 
I would like to Implement this design in this exciting rebranded website for guys.
Can you kindly assign it to me under GSSOC'23?
Thanks in advance for taking your time for this feature request.
Regards,
Jeyavishnu @vishnu9865

**Comment by darkterminal** [comment]
And try to keep GitHub, Twitter, and Toggle Theme icons for comparison so that maintainers and core developers know the comparison of the results. Good Luck! :heavy_check_mark:

**Comment by vishnu9865** [comment]
@darkterminal @vinzvinci @Mustafiz04 ,
## Is it okay that I have been developing the updated navbar as a separate component ?
 - The existing navbar had  multiple 'nav' html elements while a website is semantically supposed to have one.
 - And the code for a single navbar bar comprised of multiple files.
 - The NavbarV3.tsx component will be added in the layout.tsx file in app folder instead of existing code.

**Comment by mkubdev** [comment]
Hello @vishnu9865 😁

> The existing navbar had multiple 'nav' html elements while a website is semantically supposed to have one.

No, it's not true that a website is semantically supposed to have only one `<nav>` HTML element. The number of `<nav>` elements in a website depends on the structure and layout of the navigation system.

> And the code for a single navbar bar comprised of multiple files.

What do you mean?

> The NavbarV3.tsx component will be added in the layout.tsx file in app folder instead of existing code.

The actual navbar is called `SiteHeader` and implemented in the app/layout.tsx.
`SiteHeader` is the parent nav that take `MainNav` components children.

The actual architecture of the navbar is very well implemented, and developed by shadcn/ui. The new navbar should keep using this structure if it's only design update from the Figma in my opinion :))

**Comment by vishnu9865** [comment]
> Hello @vishnu9865 😁
> 
> > The existing navbar had multiple 'nav' html elements while a website is semantically supposed to have one.
> 
> No, it's not true that a website is semantically supposed to have only one `<nav>` HTML element. The number of `<nav>` elements in a website depends on the structure and layout of the navigation system.
> 
> > And the code for a single navbar bar comprised of multiple files.
> 
> What do you mean?
> 
> > The NavbarV3.tsx component will be added in the layout.tsx file in app folder instead of existing code.
> 
> The actual navbar is called `SiteHeader` and implemented in the app/layout.tsx. `SiteHeader` is the parent nav that take `MainNav` components children.
> 
> The actual architecture of the navbar is very well implemented, and developed by shadcn/ui. The new navbar should keep using this structure if it's only design update from the Figma in my opinion :))

@mkubdev Sir, 
 - Ofcourse sir, you are right , there is no limitation for nav elements in the website 😅😅.
 - I'm sorry, I was only mentioning it because nav has a semantic meaning and I thought why not wrap the whole navbar component in nav element rather than individual ones inside a div element.
 - And of all the code the actual navbar architecture is superb, I was only meaning to put forth the thought of going through multiple files for a change of design for what is essentially a single component ( navbar ) from the perspective of the user.
 - This especially makes change of design harder as it is hard to tell **which style of which element from which file** 👈😅 is producing a certain layout in the final outcome.

#### doubt
 - As you mentioned above if SiteHeader is the parent nav and MainNav is supposed to take children but SiteHeader itself takes Nextjs Links along with MainNav as children.

That's all sir, 😅 It's bunch of 'why not' thoughts from a beginner guy and don't quote me on these 'why nots' 😂😂 because I am learning the implications of each piece of code only now thanks to you and other mentors respectfully.

I may ask some other silly questions in the future in my quest to contribute 😅 so thanks in advance.

Thank you for taking your time to reply for this and my silliness.
Regards,
Jeyavishnu @vishnu9865

**Comment by vishnu9865** [comment]
> The new navbar should keep using this structure if it's only design update from the Figma in my opinion :))

@mkubdev I will try to not change the structure and change the design sir Thank you.
