### ISSUE TITLE
Grammatical and  spelling mistakes in the website [FEATURE]

### ISSUE THREAD

**Issue by HimanshuNarware** [WebXDAO/WebXDAO.github.io#342]
### Detailed description

Grammatical and spelling mistakes in the website,    I want to resolve them, please assign me this issue.

### Context

It improves the readability of the website

### Additional information

![1](https://github.com/WebXDAO/WebXDAO.github.io/assets/83147410/fbe5d351-9186-4e13-9886-350d9a17ff53)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
you can check

https://devprotocol.xyz/
https://the-algorithms.com/
https://twitter.com/lumoslabsHQ

**Comment by mkubdev** [comment]
Thanks for your contribution, but i'm closing this. Description are from our partners. 🙏
