### ISSUE TITLE
[FEATURE] Want to add Footer to the site 

### ISSUE THREAD

**Issue by piyush-mahajan** [WebXDAO/WebXDAO.github.io#343]
### Detailed description

The site is missing the main component which is Footer it shows user how the flow works in the website makes user journey very satisfying.

### Context

The footer is the main feature of the site when user scroll the site it makes them more interactive and the site more user friendly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
we already have footer, it is just push on v3, now on main branch!

**Comment by vinzvinci** [comment]
I'm closing this issue now. Please open a new issue if you find anything else that needs to be addressed.
