### ISSUE TITLE
[FEATURE] Change the GitHub to Guild.xyz

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/WebXDAO.github.io#344]
### Detailed description

Hey folks,

can someone change this to guild.xyz?

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/e424685c-a7be-4912-954e-00c68489f38b)

### Context

We are using https://guild.xyz/webx-dao to invite some folks to join our DAO, it would be better to highlight them on our website.

### Possible implementation

please change the GitHub to Guild.xyz
- logo and text

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SoNiC-HeRE** [comment]
I can do this, please assign it to me

**Comment by vinzvinci** [comment]
you can use this logo @SoNiC-HeRE 

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/4c5befe9-fc26-46e8-a953-6c5103a8675e)

**Comment by vinzvinci** [comment]
you can use this logo @SoNiC-HeRE 

![guild xyz](https://github.com/WebXDAO/WebXDAO.github.io/assets/73097560/e80a3488-f7e7-4352-95d3-e0ae287f074c)
