### ISSUE TITLE
[FEATURE] Improvement in Footer section . [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [WebXDAO/WebXDAO.github.io#345]
### Detailed description

Footer looks little bit off in comparative to the other parts  and even icons are not aligned properly,
Want to make some changes keeping the whole website on mind.
If changes req. do assign it to me under GSSOC 2023 .  :|)

### Context

Improvement in design

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Soulpurr** [comment]
@ManishaSwain8 can you assign this to me under gssoc23

**Comment by Mustafiz04** [comment]
@ManishaSwain8 sure you can work on this. I am assigning it to you.
Please make sure the footer looks like this.
Figma link -> https://www.figma.com/file/3DBLz1I6bI651lizseSQ0d/WebX-DAO---Website?type=design&t=Lg0Yk7hnG4tVBDnW-0

<img width="1059" alt="Screenshot 2023-05-24 at 9 15 51 PM" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/49086821/bf08bf4a-fb5f-430f-87b8-5216b18e7f8c">

**Comment by ManishaSwain8** [comment]
Got it   !!!

**Comment by Soulpurr** [comment]
Ok

**Comment by ManishaSwain8** [comment]
@Mustafiz04 Just example below, is background ok or should keep it as it is !
![Screenshot (49)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/a29a0c70-62c0-43f5-a1c6-db5d18951e8b)

**Comment by Mustafiz04** [comment]
> @Mustafiz04 Just example below, is background ok or should keep it as it is !
> 
> ![Screenshot (49)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/a29a0c70-62c0-43f5-a1c6-db5d18951e8b)
> 
> 

It is okay.
