### ISSUE TITLE
[FEATURE]:Hover effect on card item 

### ISSUE THREAD

**Issue by Soulpurr** [WebXDAO/WebXDAO.github.io#347]
### Detailed description

The card items are not that great so adding a hover effect like bouce will make them look good.
![scrnli_24_05_2023_19-14-26](https://github.com/WebXDAO/WebXDAO.github.io/assets/92094765/a2ae1a48-a0be-4a96-843e-9fbacf4b93b9)
 

### Context

The card item must be good looking as it the first thing that user see in a site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mustafiz04** [comment]
Sure @Soulpurr. I am assigning it to you.
You can add a hover effect and also make this Read More button to the center of the card.
