### ISSUE TITLE
[BUG] Mobile navbar not visible

### ISSUE THREAD

**Issue by Soulpurr** [WebXDAO/WebXDAO.github.io#348]
### Description of the bug

Navbar for mobile is not visible
Pls assign this to me under gssoc23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Good catch!

**Comment by Mustafiz04** [comment]
This is the issue. If possible please fix the rest of the responsiveness of the page.
@Soulpurr You can start working on this.
https://github.com/WebXDAO/WebXDAO.github.io/assets/49086821/9d447359-ea32-4c22-9ef0-3647c95ea0d4

**Comment by Soulpurr** [comment]
Okk

**Comment by Soulpurr** [comment]
Okk

**Comment by MAYANKpandey14** [comment]
Here #331
