### ISSUE TITLE
[BUG] Breaking of UI in mobile

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#350]
### Description of the bug

The UI breaks in mobile of landing page.
The headings should have more width and the cards should be one in a column.

### Please add screenshots (if applicable)

![photo_2023-05-25_02-16-40](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/6d217106-bddb-41de-86bb-e3319bd62895)
![photo_2023-05-25_02-16-47](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/3c702779-7ecd-450f-94b6-1e12feee4d19)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @vinzvinci @siddhi-244 @darkterminal

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by mkubdev** [comment]
Hey @s2sharpit 👋🏻 

Yes, the responsive is messy right now. We have #333 #331 and now #350.
If you want to work on it, i can assign you 😁

**Comment by darkterminal** [comment]
You got it @s2sharpit !!! 🔥

**Comment by Anmol-Baranwal** [comment]
@s2sharpit 
Is this issue resolved? So, I would like to close this.

**Comment by s2sharpit** [comment]
> @s2sharpit Is this issue resolved? So, I would like to close this.

Hey @Anmol-Baranwal and @vinzvinci 
The card widths in Blurb section appear inconsistent, and the lack of a set max-width for the descriptions results in an unappealing layout. The same issue persists on mobile and tablet, with the description width also affected.
I would like to resolve this issue like this.

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/81528d15-f6fb-48d4-a8bc-9233000ec089) | ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/99e4e06b-5675-43a2-a887-b9aed4a854e0) |
| ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/2fbb45f0-4866-404f-934d-d54cc44ebbb1) | ![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/8439751d-0898-4607-95d6-3a18b4b8cbcf) |
