### ISSUE TITLE
[BUG] Footer Section is only visible in Landing Page. 

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#351]
### Description of the bug

The footer section is only visible in Landing Page.
It should also visible in other pages like in Contributors page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @vinzvinci @siddhi-244 @darkterminal

I would like to work on this under GSSoc.
Please add the label [GSSoC23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by darkterminal** [comment]
Indeed, the footer should be accorded the same level of attention as the main navigation. And if you do intend to implement this, I kindly request that you also pay heed to the appropriate links that should be incorporated within the footer.

**Comment by s2sharpit** [comment]
> Indeed, the footer should be accorded the same level of attention as the main navigation. And if you do intend to implement this, I kindly request that you also pay heed to the appropriate links that should be incorporated within the footer.

Ya Sure, I will implement this also.
Thank you for assigning it.
