### ISSUE TITLE
[FEATURE]  Code Refactoring: Dividing Home Page Code into Section Components

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#353]
### Detailed description

I would like to raise an issue regarding the code structure of the home page.

### Context

Currently, the code for the home page is quite extensive and complex, making it difficult to locate specific sections or make modifications efficiently.

### Possible implementation

To address this concern, I propose refactoring the code by dividing the home page into smaller, more manageable section components. This approach will enhance code readability, maintainability, and reusability. By encapsulating each section's functionality and styling within separate components, it will be easier to navigate, understand, and modify the codebase.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

**Comment by darkterminal** [comment]
That is an excellent idea. We shall conduct a thorough review once your task is completed. Best of luck. 🤝🍀

**Comment by s2sharpit** [comment]
Thank you for assigning it to me. 😊
