### ISSUE TITLE
[FEATURE] Adding Pre loader in website.

### ISSUE THREAD

**Issue by ManishaSwain8** [WebXDAO/WebXDAO.github.io#356]
### Detailed description

As the new features gets added, the loading time increases ,So it will be a fair deal to add a loading page (preloader)  to make it look better and fun.

If this feature is required, do assign it to me under [GSSOC 2023].
changes will be done in no time.  :)

### Context

feature adding

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saurav-Pant** [comment]
i want to work on it

**Comment by Mustafiz04** [comment]
Assigning it to you.

**Comment by ManishaSwain8** [comment]
Hello @Mustafiz04 I need a lil bit of help !
![Screenshot (55)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/7b546483-e17f-4d0e-868f-ba1c732b4898)
I have added my code in "page.tsx" , as the navigation bar is imported from "siteCongig" it is appearing before loader ,
How should I avoid it ?

**Comment by ManishaSwain8** [comment]
![Screenshot (56)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/af5beb96-0033-40ad-a9d8-7c5f87528783)
  
this is my code !

**Comment by vishnu9865** [comment]
@ManishaSwain8, 
- I think the `page.tsx` and  `page.tsx` for other routes are essentially children components of `layout.tsx` in NextJS 13 if I am not mistaken. So, my idea would be to add your preloader to `layout.tsx`.
 - Hope you found this helpful :)) -> Please do correct me If I am wrong. 👈😅.
Regards,
Jeyavishnu @vishnu9865

**Comment by ManishaSwain8** [comment]
Okay I am trying  : |)

**Comment by ManishaSwain8** [comment]
@vishnu9865 
![Screenshot (57)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/607ab0a6-6679-439e-8da1-fe096577a2aa)
its not working though !

**Comment by vishnu9865** [comment]
@ManishaSwain8 ,
 - I'm sorry I didn't specify, I meant `app/layout.tsx` not the `components/layout.tsx`.
 - Hope this solves the issue. 😅👍

**Comment by ManishaSwain8** [comment]
Ok trying again : |)

**Comment by ManishaSwain8** [comment]
There is an runtime error saying,

*Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.*

**Comment by ManishaSwain8** [comment]
![Screenshot (58)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/2690914d-86b9-44e5-bb5f-6fac510adffb)

**Comment by vishnu9865** [comment]
Can you put lower half of the code as screenshot please

**Comment by ManishaSwain8** [comment]
![Screenshot (59)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/766c9bb8-ccf2-4432-b6ea-f0d5abd8130b)

**Comment by ManishaSwain8** [comment]
ok thanks for your help   : |)

**Comment by Mustafiz04** [comment]
Hey @ManishaSwain8 has your problem been resolved or do you still need help ??

**Comment by ManishaSwain8** [comment]
I did not get any solution to that may be I am just beginner to Next.js so thats why may be I am not getting it, My code very simple I just need to know where to put it   : |)

So you can reassign to someone else 👍

**Comment by Mustafiz04** [comment]
Don't worry. Let me check this after my work.
For now push your code whatever you have done yet. I will check after that.

**Comment by Saurav-Pant** [comment]
assign it to me, and I will go for it

**Comment by Mustafiz04** [comment]
> @vishnu9865 
> 
> ![Screenshot (57)](https://github.com/WebXDAO/WebXDAO.github.io/assets/96622693/607ab0a6-6679-439e-8da1-fe096577a2aa)
> 
> its not working though !

Try with simple H1 or p tag instead of siteheader or dna tag just to figure out whether this is loader state change issue or something else.

**Comment by vishnu9865** [comment]
@Mustafiz04 ,
Ok sir I am working on it.🚀🚀🚀

**Comment by ManishaSwain8** [comment]
Ok so I am pushing the code you can do changes to it . !

**Comment by vishnu9865** [comment]
@Mustafiz04 Sir,
I was able to achieve the said functionality but I had to make the `layout.tsx` rendered in client rather in server to achieve it. So having this feature means to have the entire home page client rendered. So, I wanted to have your thoughts about this.
Regards,
Jeyavishnu @vishnu9865

**Comment by mkubdev** [comment]
I close since #390
