### ISSUE TITLE
[FEATURE]Responsiveness of homepage

### ISSUE THREAD

**Issue by Soulpurr** [WebXDAO/WebXDAO.github.io#364]
### Detailed description

Homepage is not responsive. I would like to work on that.
Pls assign this issue to me under gssoc23

### Context

Responsive is must now a days

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hello :wave: 
Duplicate of #331 #333 #350

**Comment by Soulpurr** [comment]
Yea just raised it as it's still not completed

**Comment by mkubdev** [comment]
> Yea just raised it as it's still not completed

Yes, issues are assigned in waiting for their PR. The live website still isn't responsive yet 😄

**Comment by Soulpurr** [comment]
So how long will you wait before unassigning 😂

**Comment by vinzvinci** [comment]
> So how long will you wait before unassigning 😂

If a contributor doesn't provide an update on an issue within 2-3 days, we can unassigned. Please wait for now ^^

**Comment by Soulpurr** [comment]
Okk

**Comment by Anmol-Baranwal** [comment]
I am closing this issue since this is tagged as duplicate, you can reopen if you feel otherwise.

> One should provide clear descriptions in the issue on what you can contribute in the responsiveness.
