### ISSUE TITLE
[FEATURE] Refactor the Readme.md File 

### ISSUE THREAD

**Issue by Preetam078** [WebXDAO/WebXDAO.github.io#365]
### Detailed description

While solving my previous assigned isssue I got trouble to setup and start local server because I had **node 14v** in my local machine and your project requires minimum **node 16v** as an environment.

when Node  version < 16
![Screenshot from 2023-05-24 23-51-27](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/bf4851d1-7d8d-48c8-8636-9cf96875e815)

when Node verison >= 16 
![Screenshot from 2023-05-25 21-21-32](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/81724cd2-8bdc-4cc7-8e70-795e8e187c13)

I think this should mentioned prior in the readme.md file for the developers to make the contribution experience better.

please assign this task to me as i already experienced the issue.

### Context

I think this should mentioned prior in the readme.md file for the developers to make the contribution experience better.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hello @Preetam078 !

This is a nice idea to mention the required node >= v16 ! I assign you. :)
