### ISSUE TITLE
[FEATURE] Refactor the Blurbs code

### ISSUE THREAD

**Issue by Preetam078** [WebXDAO/WebXDAO.github.io#368]
### Detailed description

In my Previous issue #333 while improving the responsive design I noticed the codebase is not following the best ReactJs/ NextJs practices 

observe the highlighted code below:
![pages](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/f7607575-cc9d-4da1-9777-9122114c48c8)

same code is written 3 times for 3 different values 

changes i am proposing:- 
-> Make a new Component called **Blurbs.tsx** in components folder having required logic part
-> called the **Blurbs.tsx** in **pages.tsx** 3 times using the map function (higher order function) and pass  props values to the **Blurbs.tsx**
-> Blurbs component will be render we there respective values from props which is stored using array destructing method for better readability.

### Context

Making the developement experience better for developer with better coding practices

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thehashmap** [comment]
Thanks for the suggestion!
I think you can make the proposed changes in #366 itself and we can close this issue.

**Comment by Preetam078** [comment]
In #366 I just had changed and added the CSS to add responsiveness but somehow code base should need to follow some modern react practices to follow. As I mentioned in the issue description.

**Comment by mkubdev** [comment]
Hello, you can add this changes to #366 as @thehashmap mentioned!
