### ISSUE TITLE
[FEATURE] removing the repeatitive codes with javascript higher order function(Map)

### ISSUE THREAD

**Issue by Preetam078** [WebXDAO/WebXDAO.github.io#376]
### Detailed description

In my Previous issue while improving the responsive design I noticed the codebase is not following the best ReactJs/ NextJs practices

observe the highlighted code below:
![pages](https://github.com/WebXDAO/WebXDAO.github.io/assets/81969353/07df4cdf-658f-4e70-9cdc-19b03b0e0576)

same code is written 3 times for 3 different values

changes i am proposing:-
-> Make a new Component called Blurbs.tsx in components folder having required logic part
-> called the Blurbs.tsx in pages.tsx 3 times using the map function (higher order function) and pass props values to the Blurbs.tsx
-> Blurbs component will be render we there respective values from props which is stored using array destructing method for better readability.

### Context

Improve the codebase with modern and best ReactJS/ NextJS Practices. Making the developement experience better for developer with better coding practices

### Possible implementation

-> Make a new Component called Blurbs.tsx in components folder having required logic part
-> called the Blurbs.tsx in pages.tsx 3 times using the map function (higher order function) and pass props values to the Blurbs.tsx
-> Blurbs component will be render we there respective values from props which is stored using array destructing method for better readability.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Preetam078** [comment]
Hii admin please assign this task to me

**Comment by Anmol-Baranwal** [comment]
This definitely improves readability and reusability.
@vinzvinci 
What do you think?

**Comment by Anmol-Baranwal** [comment]
@Preetam078 
Are you interested in contributing?
If not, please let me know so that I can close the issue.
