### ISSUE TITLE
[BUG] Error on clicking on project. 

### ISSUE THREAD

**Issue by AditiSingh2003** [WebXDAO/WebXDAO.github.io#377]
### Description of the bug

When we click on project then the error 404 occurs.

### Please add screenshots (if applicable)

![Screenshot (44)](https://github.com/WebXDAO/WebXDAO.github.io/assets/97729662/b3099684-5827-44df-bfd2-85fdf5e57cb5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anmol-Baranwal** [comment]
This has been resolved, so closing the issue.
