### ISSUE TITLE
[FEATURE] Hovering Effect

### ISSUE THREAD

**Issue by parthpathakpp1** [WebXDAO/WebXDAO.github.io#382]
### Detailed description

Currently this boxes and twitter and discord logo does not have any hovering effect . 
![webxdaoblockchainhoveringtwitter](https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/b710aa00-d502-4700-bb52-a366395f4af2)

### Context

It will look good . 

### Possible implementation

Will make those boxes do some animations while hovering . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by Mustafiz04** [comment]
@parthpathakpp1 assigning it to you.

**Comment by parthpathakpp1** [comment]
I have raised a PR https://github.com/WebXDAO/WebXDAO.github.io/pull/412
