### ISSUE TITLE
[BUG] Community Partners 

### ISSUE THREAD

**Issue by parthpathakpp1** [WebXDAO/WebXDAO.github.io#383]
### Description of the bug

When we hover on Community Partners cards . It goes on top of navbar . Technically it should be under navbar on hovering also.

### Please add screenshots (if applicable)

https://github.com/WebXDAO/WebXDAO.github.io/assets/85991449/f02cb6a6-d9b2-4ab9-bd77-f85d1300ae93

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by Mustafiz04** [comment]
@parthpathakpp1 assigning it to you.

**Comment by parthpathakpp1** [comment]
I have raised a PR https://github.com/WebXDAO/WebXDAO.github.io/pull/410
