### ISSUE TITLE
Improving Contributors page 

### ISSUE THREAD

**Issue by programerr01** [WebXDAO/WebXDAO.github.io#386]
### Detailed description

Adding User's Profile Picture in the page.
Also, page is not consistent with overall design of page 

### Context

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/61112300/55a8a854-83a1-4a04-b67a-378c839bfee3)

### Possible implementation

profile data is already coming so shouldn't be issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mustafiz04** [comment]
@programerr01 go for it,

**Comment by Anmol-Baranwal** [comment]
@programerr01 
Are you interested in contributing?
If not, please let me know so that I can close the issue.
