### ISSUE TITLE
[FEATURE] Implement 404 Page according to V3 design [GSSoC'23]

### ISSUE THREAD

**Issue by vishnu9865** [WebXDAO/WebXDAO.github.io#387]
### Detailed description

 - Implement 404 page according to V3 figma file

### Context

 - The current page is blank and do not align with design of the website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by omlondhe** [comment]
May I work on this issue?
I am GSSoC 2023 contributor.

**Comment by Vidip-Ghosh** [comment]
May I work on this issue under GSSoC'23 ?

**Comment by Mustafiz04** [comment]
@vishnu9865 are you going to work on this?

**Comment by vishnu9865** [comment]
@Mustafiz04 Yes sir I would like to contribute to the project regarding implementing this page.
