### ISSUE TITLE
[BUG] Navbar, Footer not taking full width.

### ISSUE THREAD

**Issue by Vidip-Ghosh** [WebXDAO/WebXDAO.github.io#389]
### Description of the bug

Navbar and Footer aren't taking the full width in Contributors section of mobile device less than 400px width. 
Also, dark and light mode toggle not visible in smaller devices. 

### Please add screenshots (if applicable)

<img width="321" alt="Screenshot 2023-05-28 at 22 42 08" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/91741581/522cc118-2352-4c1e-b8fe-f8f7f5aad656">

<img width="485" alt="Screenshot 2023-05-28 at 22 45 05" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/91741581/f5c9718b-311f-4280-aff4-738bec48900c">

### Add any other context about the problem here

Please assign this issue under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mustafiz04** [comment]
@Vidip-Ghosh Assigning it to you.

**Comment by mkubdev** [comment]
Hello 👋🏻 
Sorry but this is already fixed by 67b03271a4143ca02c80fc3caca2f1086e5f2f81 (Test on: https://webxdao.xyz/). So i'm afraid that we should close this issue... @WebXDAO/gssoc-mentors
