### ISSUE TITLE
[FEATURE] Add a custom scroll-bar.

### ISSUE THREAD

**Issue by abhinav-m22** [WebXDAO/WebXDAO.github.io#391]
### Detailed description

Change the basic scroll bar to a custom stylish scroll bar which matches the theme of the website.
It will improve the overall design and UX of the web page.

### Context

A custom scrollbar adds uniqueness and originality to the design, making it more fascinating for users.

### Additional information

I want to work on this feature implementation.
Please assign me the task under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mustafiz04** [comment]
@abhinav-m22 go for it.
assigning it to you.
