### ISSUE TITLE
[OTHER] Update Issue forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [WebXDAO/WebXDAO.github.io#393]
### What would you like to share?

The current issue form template can be improved:

- We can directly ask the author of the issue if they are a GSSoC'23 Contributor.
- Additionally, we can inquire if they want to work on the issue with proper validation. This will eliminate the need for an extra comment tagging admins and collaborators to assign the issue and add appropriate labels.
- The code of conduct is repeated twice, while the contributing guidelines should be included in the checklist instead.

### Additional information

I would update all the issue forms with a proper checklist.

You can check out my work on GitHub issue forms in this pull request: https://github.com/dailydotdev/daily/pull/864. It demonstrates my familiarity with the concept and implementation.

> I want to work on this under GSSoC. Once you assign me, I will start working on the issue.

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Hey Anmol 👋 

This is a good idea! Soon we can also use this idea on hacktoberfest :) You can start working on this now!
