### ISSUE TITLE
[BUG] Partner Section's Card on Hover render over the navbar . 

### ISSUE THREAD

**Issue by MAYANKpandey14** [WebXDAO/WebXDAO.github.io#395]
### Card on hover increase in size and render over the navbar decreasing it effectiveness
Also if we look carefully the middle card of the three don't have rounded corners on the top side .

### Please add screenshots (if applicable)

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/ae65b2b4-f82b-4650-9313-281091f90628)

![Screenshot 2023-05-31 000119](https://github.com/WebXDAO/WebXDAO.github.io/assets/94740455/4c59aaba-c750-4622-b4ec-f13776a61e56)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev

I would like to work on this under GSSoc.
Please add the label gssoc23.
And assign it to me.

धन्यवाद
