### ISSUE TITLE
[BUG] The Icon for theme toggle on the website should be changed 

### ISSUE THREAD

**Issue by abhiraj-ku** [WebXDAO/WebXDAO.github.io#397]
### Description of the bug

The icon that is current displaying for dark theme is sun icon which in this case should be moon and for the light mode it should be sun icon .

I want to work on this this issue and fix this . I am participating under GSSOC '23

### Please add screenshots (if applicable)

![webxdao](https://github.com/WebXDAO/WebXDAO.github.io/assets/113116498/9f5bb6b3-1981-432f-8ee3-b6836d7941a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tarunsamanta2k20** [comment]
Can I take this issue up?

**Comment by Anmol-Baranwal** [comment]
@abhiraj-ku 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
