### ISSUE TITLE
💡 [FEATURE]: ACCESSIBLE SOCIAL ANCHORS ON FOOTER

### ISSUE THREAD

**Issue by 0xabdulkhalid** [WebXDAO/WebXDAO.github.io#398]
### Description

- This issue is about adding `aria-label` for social anchors (links like Github) which are placed inside the `footer` element

- it is important to note that we want to add the `title` attribute also. This is because the `title` attribute is intended to provide additional information to screen reader users.

- The `aria-label` attribute is a way more important for providing accessibility information to screen reader users. The `aria-label` attribute is an Accessible Rich Internet Applications (ARIA) attribute that can be used to provide a label for an element. This label is then read aloud by screen readers, providing additional information about the element to the user.

- In general, the `aria-label` & `title` attributes are preferred for providing accessibility information to screen reader users.

- You can consider to assign this issue to me to make the site accessible for screen readers

### Screenshot (Going to make changes on these elements)
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/92252895/777624ac-e7a7-46e1-89a6-c78fb8f0b027)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Wow, Bro you're just suprising me!!

PS: Kindly add `gssoc23` and appropriate `level` for this issue so that `GSSoC'23`'s Backend can take account of this Contribution. Thanks!

**Comment by mkubdev** [comment]
> Wow, Bro you're just suprising me!!
Hahaha! Why so?!
> PS: Kindly add `gssoc23` and appropriate `level` for this issue so that `GSSoC'23`'s Backend can take account of this Contribution. Thanks!
Sure! But the label is only required on the PR, like Hacktoberfest. So feel free to open a PR, reference this issue to close it automaticly, and then we add `gssoc` and `level` label! 😋

**Comment by 0xabdulkhalid** [comment]
Thanks Bro for pointing this out, i make the work done!
