### ISSUE TITLE
[BUG] Inconsistent Placement of Hamburger Toggle and Navbar Opening Direction

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#399]
### Description of the bug

Currently, the hamburger toggle (the three horizontal lines) is positioned on the right side of the screen. However, when the hamburger toggle is clicked, the navbar opens towards the left side of the screen. This inconsistency in placement and opening direction can cause confusion and disrupt the overall user experience.

## Expected Behavior:
Ideally, the hamburger toggle and the direction in which the navbar opens should be aligned to provide a consistent user experience. If the hamburger toggle is positioned on the right side, the navbar should open towards the right side as well. Alternatively, if the navbar is intended to open towards the left side, the hamburger toggle should be placed on the left side of the screen.

### Please add screenshots (if applicable)

![WhatsApp Image 2023-05-31 at 20 39 24](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/1c7296fe-48d2-46ea-8450-c9b3614d0b78)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by Anmol-Baranwal** [comment]
@vinzvinci 
What do you think on this?
