### ISSUE TITLE
[BUG] Project Page Width Exceeding Screen Width

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#400]
### Description of the bug

I hope this message finds you well. I am writing to report an issue regarding the width of the projects page on our website, which is causing it to exceed the width of the screen.

Currently, when accessing the projects page, the content extends beyond the screen boundaries, making it difficult for users to view and interact with the page properly. This issue affects the overall user experience and hampers the accessibility of the project information.

Affected Page: https://webxdao.xyz/projects
Screen Resolution: 1920 x 1080
Device: Laptop

### Please add screenshots (if applicable)

https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/15f8c196-05d9-4b18-959f-3f70986c5ad8

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by Faizan711** [comment]
Hey, is this issue assigned to anyone. If not, i would like to fix it and make a PR.

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7 @Mustafiz04

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
Please check this issue.

**Comment by s2sharpit** [comment]
Hey @Anmol-Baranwal 
I have raised the pr #453 for this issue. Have a look and review it.

धन्यवाद 😊
