### ISSUE TITLE
[BUG] Fix Projects Card according to V3 design [GSSoC'23]

### ISSUE THREAD

**Issue by vishnu9865** [WebXDAO/WebXDAO.github.io#401]
### Description of the bug

 - The projects card has different layout of information than the figma file.
 - The layout of the projects card with different width breakpoints change the projects card width.
 - Fix or update Read More button design.
 - Add box shadows based on v3 design.

### Please add screenshots (if applicable)

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/e32a7328-7c93-40d8-b327-cd04e9e13832)
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/4cd6d429-2cf6-4c01-908a-0b2ff948e94f)

### Add any other context about the problem here
Expected Projects card
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/91585213/d4c4a363-e20e-4e40-9146-401a72f7a30c)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by vishnu9865** [comment]
@shuklaritvik06 I would like to work on this issue.
Please kindly assign it to me. 
Regards,
@vishnu9865

**Comment by shuklaritvik06** [comment]
> @shuklaritvik06 I would like to work on this issue. Please kindly assign it to me. Regards, @vishnu9865

Go Ahead Vishnu 🚀
