### ISSUE TITLE
[OTHER] Add codeowners

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#403]
### What would you like to share?

By adding code owners, we can request a review from those people in every PR.
We can add the most active maintainers/people, or just the whole GitHub team.

We can also customize who are the code owners of certain files (e.g. `.md` files are owned by `user`).

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @Panquesito7 
Can we collaborate on this issue?

**Comment by Panquesito7** [comment]
Sure, let's work on it together.
Are you on the Discord server?

**Comment by s2sharpit** [comment]
> Sure, let's work on it together. Are you on the Discord server?

धन्यवाद for giving me this opportunity.
Yaa, I'm in the Discord server.

**Comment by Anmol-Baranwal** [comment]
Please ask the moderators to assign the task, so that we can directly filter which tasks are assigned to nobody.

**Comment by s2sharpit** [comment]
> Please ask the moderators to assign the task, so that we can directly filter which tasks are assigned to nobody.

Sure @Anmol-Baranwal @Panquesito7

**Comment by Panquesito7** [comment]
I believe the core maintainers should be codeowners of all the files.
Krish can be added to one of the most important, if not, all the files as well.
I can be assigned the documentation files and other minor files, such as the contributing guidelines, the GH Actions workflows, etc..

**Comment by Anmol-Baranwal** [comment]
> I believe the core maintainers should be codeowners of all the files. Krish can be added to one of the most important, if not, all the files as well. I can be assigned the documentation files and other minor files, such as the contributing guidelines, the GH Actions workflows, etc..

Everyone can decide on that when the pull request (PR) with sample values is raised, making it easier to implement.
