### ISSUE TITLE
[FEATURE]Implement Lazy Loading in the WebXDOA project

### ISSUE THREAD

**Issue by Preetam078** [WebXDAO/WebXDAO.github.io#416]
### Detailed description

Hii Team, 
I want to add a feature called Lazy Loading in your Nextjs Application this technique used to optimize the loading of components and improve the overall performance of your WebXDAO application. Normally, when your application loads, all the components are bundled together and sent to the browser. This means that even if the user doesn't need or interact with certain components immediately, they are still loaded upfront, potentially slowing down the initial page load.

Please assign this issue to me under GSSoC 23

### Context

Lazy loading allows you to split your WebXDAO application into smaller chunks or bundles and load them on-demand, only when they are needed. This way, you can reduce the initial load time and improve the user experience.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by mkubdev** [comment]
Hello! That's sound good, i assigned you :)

**Comment by Anmol-Baranwal** [comment]
@Preetam078 
Are you interested in contributing?
If not, please let me know so that I can close the issue.
