### ISSUE TITLE
[BUG] Projects and Contributors page title is not changing as the page changes

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#418]
### Description of the bug

The Projects and Contributors page title is not changing when we are on that page respectively.

The title should be like :
For Projects Page:             Projects | WebXDAO
For Contributors Page:      Contributors | WebXDAO

### Please add screenshots (if applicable)

Projects Page:

<img width="953" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/a5b5f5ef-edb3-47c7-aab6-d5f736c7b4e9">

Contributors Page:

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/eba30186-20e6-4b5c-b453-73dd441029d5)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7 @Mustafiz04

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7 @Mustafiz04

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
Please check this issue also

**Comment by Anmol-Baranwal** [comment]
In my opinion, having a single title is more impactful and conveys a sense of consistency and branding.

**Comment by s2sharpit** [comment]
Hey @vinzvinci
What's your perspective on it?

**Comment by Anmol-Baranwal** [comment]
@mkubdev 
Please share your opinion so that we can resolve this accordingly.

**Comment by mkubdev** [comment]
> In my opinion, having a single title is more impactful and conveys a sense of consistency and branding.

Yeah or we can customize them as `WebXDAO - <page title>` what do you think? 

@s2sharpit What implementation you suggest?

**Comment by s2sharpit** [comment]
> Yeah or we can customize them as `WebXDAO - <page title>` what do you think?
> 
> @s2sharpit What implementation you suggest?

Hey @mkubdev,

I've been considering the implementation options, and I believe adding the page title before "WebXDAO" would be a better approach. This modification will help create a clearer association between the customized elements and their respective page titles. For example, instead of `WebXDAO - <page title>`, it would be `<page title> - WebXDAO`.

What do you think about this suggestion? If you agree, I would be happy to take ownership of this issue and start working on it.

Looking forward to your feedback.

**Comment by mkubdev** [comment]
I agree, your suggestion looks better. Ok, I assign you! 👍
