### ISSUE TITLE
[OTHER] Unnecessary stuff in tailwind.config.js

### ISSUE THREAD

**Issue by xkrishguptaa** [WebXDAO/WebXDAO.github.io#425]
### What would you like to share?

In tailwind config we have:
https://github.com/WebXDAO/WebXDAO.github.io/blob/main/tailwind.config.js#LL17C20-L17C20
we only use it like once, wouldn't it make much more sense to use the `z-[999]` wa

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@xkrishguptaa 
Are you working on this?

**Comment by xkrishguptaa** [comment]
It says `awaiting triage`?

**Comment by Anmol-Baranwal** [comment]
> It says `awaiting triage`?

Sorry, we often forget to remove tags. Please feel free to tag me if you'd like me to assign the issue. This way, it won't get lost in the sea of notifications. Thanks!

You can proceed now.
