### ISSUE TITLE
[BUG] Use new Discord invitation link

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#428]
### Description of the bug

In the issue templates configuration, there's a link to WebXDAO's Discord community.
However, the file's using the direct Discord link, which makes it look unclean and does not match the new, clean link being used.

_Steps to contribute_

1. Fork the repository [here](https://github.com/WebXDAO/WebXDAO.github.io/fork).
2. Create a new branch named `new_discord_link`.
3. Open the `.github/ISSUE_TEMPLATE/config.yml` file.
4. Edit the Discord invitation link to `https://discord.webxdao.xyz`.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/WebXDAO/WebXDAO.github.io/compare) to compare your changes.
7. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help, let us know and we'll gladly help!

### Add any other context about the problem here

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Panquesito7** [comment]
**NOTE:** This should be updated in the `.github` repository to reflect all the other repositories as well.

**Comment by vishnu9865** [comment]
@Panquesito7 Sir Can I be assigned this issue under GSSoC'23
Thanks in advance.
Jeyavishnu @vishnu9865

**Comment by shuklaritvik06** [comment]
> @Panquesito7 Sir Can I be assigned this issue under GSSoC'23 Thanks in advance. Jeyavishnu @vishnu9865

Hey Vishnu 👋🏼  Sorry for the late reply, this issue is solved by the PR #429 . I am sorry for not replying on your comment related to assigning of the issue.
