### ISSUE TITLE
[FEATURE] Link only specific GitHub projects

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#430]
### Detailed description

Currently, the projects page is fetching all of our GitHub repositories (including repositories such as `.github`).
I suggest we link specific projects only, such as the Blockchain Development Path, our website, and other repositories.

### Context

This will make it much cleaner as well as let the community know the best WebXDAO projects.

### Possible implementation

Link only the best WebXDAO projects and resources on the projects page.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by Riyazul555** [comment]
Hey @Anmol-Baranwal I want to work on this issue.... please assign me this

**Comment by Anmol-Baranwal** [comment]
@Riyazul555 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by Riyazul555** [comment]
Hey @Anmol-Baranwal and @Panquesito7 could you please make it more specific what projects who want to show rather than showing all repos

**Comment by Riyazul555** [comment]
Hey @Anmol-Baranwal can you provide me the link of the repos you want to showcase in your project folder

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal can you provide me the link of the repos you want to showcase in your project folder

He already mentioned it clearly.
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/7704cf45-30b2-4c0b-a024-765231e4ae0f)

We don't want sub-sections in the projects section.
