### ISSUE TITLE
[BUG]: errors and warnings reported on browser's console

### ISSUE THREAD

**Issue by harmeetsingh11** [WebXDAO/WebXDAO.github.io#431]
### Description of the bug

There are some errors and warnings reported on the browser's console when website is loaded. It needs to be fixed.

### Enviroment:
- OS: Windows
- Browser: Chrome

### Please add screenshots (if applicable)

![1](https://github.com/WebXDAO/WebXDAO.github.io/assets/130365071/c515d8c6-6fc0-43f7-9102-6acfe000dc91)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@harmeetsingh11 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

> You can use https://pagespeed.web.dev/ for insights on fixing those errors
