### ISSUE TITLE
[FEATURE] In the team page, for the members involved, add some images

### ISSUE THREAD

**Issue by swapn652** [WebXDAO/WebXDAO.github.io#436]
### Detailed description

In the WebX Team page, the members have an empty white profile picture. We can include some images in that place to make it look more interactive.

### Context

The design as such doesn't look too eye catching but rather bland.
<img width="1349" alt="Screenshot 2023-06-19 at 7 42 07 PM" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/70851202/7494a596-82c0-465e-92af-5416e4ce6397">

### Possible implementation

We can include images of animated characters or of random people from free images on the internet.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by krishstwt** [comment]
Why random people? We can just use the avatar from their github ✔️

**Comment by vinzvinci** [comment]
use github.com/username.png

**Comment by vinzvinci** [comment]
https://github.com/vinzvinci
https://github.com/KukretiShubham
https://github.com/shuklaritvik06
https://github.com/mkubdev

Please also add our core designers
https://github.com/mynrjad
https://github.com/ezekiellavapiez

Moderators
https://github.com/Panquesito7
https://github.com/krishstwt

**Comment by swapn652** [comment]
@krishstwt sure we can do that too

**Comment by swapn652** [comment]
@vinzvinci can I work on this. Can you assign me?

**Comment by vinzvinci** [comment]
> @vinzvinci can I work on this. Can you assign me?

yes

**Comment by vinzvinci** [comment]
I'm taking this issue.
