### ISSUE TITLE
[Adding links in the footer section (right side)

### ISSUE THREAD

**Issue by anuza08** [WebXDAO/WebXDAO.github.io#437]
### Detailed description

[
![Screenshot (44)](https://github.com/WebXDAO/WebXDAO.github.io/assets/98256478/57c68c77-0237-4feb-934c-e9b8eeebcf5e)
]

Adding links in the about us and contact us page.
Who are we? -> will direct to landing page.
what we do? -> will direct to this section
[
![Screenshot (45)](https://github.com/WebXDAO/WebXDAO.github.io/assets/98256478/0d9b5a6d-5e6b-4794-988d-663ee1a39d1a)
]

Teamwebx -> teamwebx page

### Context

It will improve the UX

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@anuza08 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
