### ISSUE TITLE
[FEATURE] Adding Hovering Effects on NavBar

### ISSUE THREAD

**Issue by PatilHarshh** [WebXDAO/WebXDAO.github.io#441]
### Detailed description

adding hovering effects on navbars looks good

### Context

.
![Screenshot (99)](https://github.com/WebXDAO/WebXDAO.github.io/assets/120102234/f35463c3-6952-42a0-8aa4-bb8d98aedf5b)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by PatilHarshh** [comment]
@vinzvinci please assign this to me @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
This is already covered in #422

> Duplicate issue.
