### ISSUE TITLE
[FEATURE] Implementing new design of Contribution Page

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#446]
### Detailed description

Wanna apply the new design of cards for contribution page and add title and subtitle at the top of page.

<img width="483" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/18211975-a800-4892-8789-3a833c4f38c5">

### Context

It will enhance the contribution page.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @darkterminal @vinzvinci @siddhi-244 @mkubdev @Panquesito7 @Mustafiz04

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by Anmol-Baranwal** [comment]
Let others review, I will not assign unless others confirm whether this is required or not.

**Comment by s2sharpit** [comment]
Hey @vinzvinci 
Please give your perspective on this.

**Comment by Anmol-Baranwal** [comment]
@mkubdev 
Do you think this is needed? or the current design works.

**Comment by mkubdev** [comment]
Hello @s2sharpit, yes let's go! I assign you 🚀

**Comment by s2sharpit** [comment]
Hey @Anmol-Baranwal @vinzvinci 
I'm not able to get the links of LinkedIn and twitter of the contributors to add the links in the contributor card.
I didn't find any links of LinkedIn and twitter in this API: https://api.github.com/repos/WebXDAO/WebXDAO.github.io/contributors?anon=1
Can you help me in that.

**Comment by s2sharpit** [comment]
> Don't do so. Rather just put the link to their commit history and github profile. At least that is what I would do. Let others give a suggestion.
> 
> You can find a commit history using `login` from the api, and use it to find other info using `https://api.github.com/users/<username>`
> 
> I recently worked on this, so I know.

Hey @Anmol-Baranwal @vinzvinci 

I have raised the PR that includes the GitHub links of the contributors for the contributor card. However, I'm facing difficulties in adding the commit history of the users.

Based on the previous suggestion, it was mentioned that adding the link to the commit history and the GitHub profile would be sufficient. I have already included the GitHub profile links, and now I would like to request @Anmol-Baranwal to kindly add the commit history if it is deemed necessary for the contributor card.

**Comment by Anmol-Baranwal** [comment]
> > Don't do so. Rather just put the link to their commit history and github profile. At least that is what I would do. Let others give a suggestion.
> > 
> > You can find a commit history using `login` from the api, and use it to find other info using `https://api.github.com/users/<username>`
> > 
> > I recently worked on this, so I know.
> 
> Hey @Anmol-Baranwal @vinzvinci 
> 
> I have raised the PR that includes the GitHub links of the contributors for the contributor card. However, I'm facing difficulties in adding the commit history of the users.
> 
> Based on the previous suggestion, it was mentioned that adding the link to the commit history and the GitHub profile would be sufficient. I have already included the GitHub profile links, and now I would like to request @Anmol-Baranwal to kindly add the commit history if it is deemed necessary for the contributor card.

You should dynamically fetch the data. What do you mean, I should add?

**Comment by s2sharpit** [comment]
Hey @Anmol-Baranwal,

Thank you for your response. I apologize for any confusion caused by my previous message. When I mentioned adding the commit history, I was referring to dynamically fetching the data rather than manually inputting it.

To clarify, could you please advise me on the best approach to dynamically fetch and include the commit history in the contributor card? I want to ensure that the card displays the relevant information accurately.

Thank you for your guidance and support. I appreciate your help in resolving this matter.

**Comment by Anmol-Baranwal** [comment]
Sorry for mass tagging; I just want to discuss the design. Additionally, could you please suggest what structure would be ideal for the design?

You have to use `async/await` and use this API endpoint: [https://api.github.com/repos/WebXDAO/WebXDAO.github.io/contributors](https://api.github.com/repos/WebXDAO/WebXDAO.github.io/contributors).

From there, you will find the `login` and the number of contributions.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/edb6a437-e462-40c7-8f38-382c6ce870d2)

Then, using the login (which is the username of the GitHub profile), we can use the following API endpoint: `https://api.github.com/users/<path_to_login_field>`. 

From this, you can retrieve the `avatar_url`, which is the profile photo of the GitHub profile, along with other information.

For example, if we retrieve `mkubdev` as the login, we can use the second API to fetch the user's data.

**Comment by Anmol-Baranwal** [comment]
> Hey @Anmol-Baranwal,
> 
> Thank you for your response. I apologize for any confusion caused by my previous message. When I mentioned adding the commit history, I was referring to dynamically fetching the data rather than manually inputting it.
> 
> To clarify, I would like to know if there are any specific steps or suggestions you have regarding how to dynamically fetch and incorporate the commit history into the contributor card, it would be greatly appreciated.
> 
> Thank you for your guidance and support. I appreciate your help in resolving this matter.

You have to use `async/await` and use this API endpoint: [https://api.github.com/repos/WebXDAO/WebXDAO.github.io/contributors](https://api.github.com/repos/WebXDAO/WebXDAO.github.io/contributors).

From there, you will find the `login` and the number of contributions.

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/edb6a437-e462-40c7-8f38-382c6ce870d2)

Then, using the login (which is the username of the GitHub profile), we can use the following API endpoint: `https://api.github.com/users/<path_to_login_field>`. 

From this, you can retrieve the `avatar_url`, which is the profile photo of the GitHub profile, along with other information.

For example, if we retrieve `mkubdev` as the login, we can use the second API to fetch the user's data.
