### ISSUE TITLE
[FEAT] - create a slider and add active member cards 

### ISSUE THREAD

**Issue by KukretiShubham** [WebXDAO/WebXDAO.github.io#45]
![ss](https://user-images.githubusercontent.com/57281769/134526606-2981b258-2d74-47de-a39d-307269b65646.png)

Create cards of people active in the community and make them sliding so that one can look through them all.

**Comment by vinzvinci** [comment]
Great idea

**Comment by mkubdev** [comment]
Great idea, look like it's time to get nestjs out!

**Comment by vinzvinci** [comment]
Hmm, any update to this? 

I want to know what it will look like.

**Comment by vinzvinci** [comment]
![image](https://user-images.githubusercontent.com/73097560/135218199-802e91a8-de46-4ae8-a1fd-686cfbe0e33d.png)

how about this idea?

**Comment by mkubdev** [comment]
> ![image](https://user-images.githubusercontent.com/73097560/135218199-802e91a8-de46-4ae8-a1fd-686cfbe0e33d.png)
> 
> how about this idea?

I like this idea. We can store .json or .md files in the website _data folder. Then the community can make PR of their own .json or .md files to add their profile circle on the website.

**Comment by krishguptadev** [comment]
> > ![image](https://user-images.githubusercontent.com/73097560/135218199-802e91a8-de46-4ae8-a1fd-686cfbe0e33d.png)
> > how about this idea?
> 
> I like this idea. We can store .json or .md files in the website _data folder. Then the community can make PR of their own .json or .md files to add their profile circle on the website.
> 
> If we need active members or best contributors, we can fetch Github API.

Fetching the GitHub API is the best in my opinion. Get everyone from the members list in the org

**Comment by krishguptadev** [comment]
then sort based upon contributions if we ever need

**Comment by krishguptadev** [comment]
This can be used for the members list: https://docs.github.com/en/rest/reference/orgs#list-organization-members.

I am thinking of using the 3 GitHub Contributions Mechanism. And using the advanced search to give points and then sorting based "upon the points \=| alphabetical alignment" (This is a mathematical equation that would sort the stuff).

The points will be calculated by 3 factors. Commits, Issues, Involvement.

These are the examples of how we are going to search for these if for example @vinzvinci were the user the points were being calculated for:

Commits: https://github.com/search?q=org%3Aweb3community+author%3Avinzvinci&type=commits
Issues: https://github.com/search?q=org%3Aweb3community+author%3Avinzvinci&type=issues
Involvement: https://github.com/search?q=org%3Aweb3community+involves%3Avinzvinci+-author%3Avinzvinci&type=issues

We would measure the length of the json response we get and then multiply the type by the unit point:

Commits = 2points
Issues = 4points
Involvement = 3points

Note that Issues include prs as per github

Then we would add them up.. And finally if 2 people have the same points we would use the alphabetical alignment using the sort method on arrays

Feel free to improve and change my algorithm if it doesn't fit the needs

**Comment by vinzvinci** [comment]
Thanks for sharing here as well. I really like your idea, anyone can start to work with this issue.

**Comment by mkubdev** [comment]
@krishguptadev Like this idea. :)

**Comment by krishguptadev** [comment]
Cool 🚀 As per our conversation in the discord channel. This issue is kept for #Hacktoberfest Participants

**Comment by Vinyl-Davyl** [comment]
Would definitely be a nice thing to hop on

**Comment by krshkodes** [comment]
Hey people, have you seen orbit.love ?

**Comment by vinzvinci** [comment]
We are doing [website v3](https://github.com/orgs/WebXDAO/projects/9/views/1). 

Closing this now! Thanks for collaboration!
