### ISSUE TITLE
Footer does not seem to be separated from the page in dark mode

### ISSUE THREAD

**Issue by Illaf** [WebXDAO/WebXDAO.github.io#450]
### Detailed description

In the dark mode ,the footer seems to be merged in the page itself

### Context

defining the footer by improving the UI so that it seems to be a separate column

### Additional information

![Screenshot (6)](https://github.com/WebXDAO/WebXDAO.github.io/assets/114517448/90b9073c-8b46-4436-8fdf-10e702ca34e9)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@Illaf 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

> Also, make sure to do significant good changes.
