### ISSUE TITLE
links in the footer section are not clickable

### ISSUE THREAD

**Issue by Illaf** [WebXDAO/WebXDAO.github.io#451]
### Description of the bug

The links under about section,contact section and partner section in the footer do not direct to the required page  

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
Duplicate of #437
