### ISSUE TITLE
[FEATURE] Scroll to Top button doesn't match theme

### ISSUE THREAD

**Issue by kaashikaagrawal** [WebXDAO/WebXDAO.github.io#456]
### Detailed description

The current scroll to top doesn't match the theme of the website. I can modify the css of the button to match the theme of the scroll bar.

### Context

It will enhance the look of the the site and enhance the UI as well.

### Possible implementation

I will modify the css of the button to match the scroll bar.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Riyazul555** [comment]
Hey @Anmol-Baranwal I want to work on this issue.... please assign me this

**Comment by Anmol-Baranwal** [comment]
@Riyazul555 
What are you planning to change? Please describe the changes you would make.

**Comment by Riyazul555** [comment]
@Anmol-Baranwal I would like add hover effect on the top scroll button to look more illustrative and make its css match the theme

**Comment by Anmol-Baranwal** [comment]
@Riyazul555 
Could you please do something like this but in dark mode, except for the logo part, which should have a slight shadow that suits the dark theme of this codebase.

> Image
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/74038190/db424765-221b-44b4-9b52-8d20f2b1dfd2)

**Comment by Anmol-Baranwal** [comment]
If you are unable to make something like this, stick to your original idea. Others will review the changes.

**Comment by Riyazul555** [comment]
[#465](https://github.com/WebXDAO/WebXDAO.github.io/pull/465)

**Comment by Riyazul555** [comment]
#465

**Comment by Riyazul555** [comment]
@Anmol-Baranwal I made a new pR .......please check pR #465 for this issue..........For some reasons I an unable to link the pR .......Thanks
