### ISSUE TITLE
[BUG] Navbar dropdown does not close when clicking outside or scrolling

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#459]
### Description of the bug

When the navbar dropdown is open and a user clicks outside of it or scrolls, the navbar dropdown should close automatically. Currently, this functionality is missing, causing inconvenience and inconsistent behavior for users.

### Please add screenshots (if applicable)

https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/af8544b5-9066-417b-b51c-8b57a6989d8a

### Add any other context about the problem here

**Expected Behavior:**
The navbar dropdown should close when the user clicks outside of it or scrolls the page.

**Actual Behavior:**
The navbar dropdown remains open even when the user clicks outside of it or scrolls the page.

**Potential Solution:**
One possible solution could be to add event listeners to detect clicks outside of the navbar dropdown or scroll events and trigger the closure of the dropdown when these events occur.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @vinzvinci @Anmol-Baranwal 

I would like to work on this under GSSoc.
Please add the label [gssoc23](https://github.com/WebXDAO/WebXDAO.github.io/labels/GSSoC23).
And assign it to me.

धन्यवाद

**Comment by Anmol-Baranwal** [comment]
@s2sharpit 
There is no need to tag everyone and ask for assigning the issue, and please refrain from mentioning GSSoC again, as you have already mentioned it in the issue form. 😅
