### ISSUE TITLE
[Add hover effect on Navbar items]

### ISSUE THREAD

**Issue by akshaysoni10** [WebXDAO/WebXDAO.github.io#466]
### Detailed description

I want to add hover effect on Navbar items to make it more attractive.

### Context

This change looks more attractive.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by hetashridk** [comment]
Hey @akshaysoni10 , I can add hover effect on navigation bar. You can assign me
