### ISSUE TITLE
[FEATURE]: Sitemap.xml

### ISSUE THREAD

**Issue by Killer2OP** [WebXDAO/WebXDAO.github.io#468]
### Detailed description

A sitemap is a file that lists all the pages of a website, helping search engines understand its structure and content.

### Context

 It enhances search engine optimization (SEO) efforts by improving website visibility and indexing. I believe adding sitemap would be a perfect addition to this project.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Killer2OP** [comment]
@Anmol-Baranwal  Can you assign me this issue.

**Comment by Anmol-Baranwal** [comment]
@Killer2OP 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
