### ISSUE TITLE
[FEATURE]: Improvement in UI in footer section

### ISSUE THREAD

**Issue by Yashika-Agrawal** [WebXDAO/WebXDAO.github.io#470]
### Detailed description

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/97408966/575ee56e-f7e3-4fb7-bfbb-f07b72ba7206)
I would like to raise an issue regarding the alignment and layout of the footer links on the project's website. Currently, the social links are aligned to the left, and the "About Us" and "Contact" links are aligned to the right. However, I believe that a more elegant and visually appealing design can be achieved by center-aligning social links and placing the "About Us" and Contact links above them. Additionally, I suggest adding a "2023 © All Rights Reserved" statement at the bottom center.

### Context

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/97408966/cc97770e-af43-486f-81cf-849aa328ef3d)
I want to make something like this.

By aligning the logo and social links in the center, placing the "About Us" links above them, and adding the "Contact" links next, the footer section will have an improved visual layout. The addition of a "2023 © All Rights Reserved" statement will also enhance the professional appearance and ensure compliance with copyright requirements.

### Possible implementation

To achieve the desired alignment and layout, I propose the following changes to the footer section:

1.Center-align the logo and social links, creating a visually balanced composition.
2.Position the "About Us" links above the centered elements, allowing for easy access and clear separation from the "Contact" links.
3.Place the "Contact" links next to the centered elements, ensuring continuity and logical flow.
4.Add a "2023 © All Rights Reserved" statement below the aligned elements, providing the necessary copyright information.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Yashika-Agrawal** [comment]
@Anmol-Baranwal , Hey please assign me this issue under GSSOC'23  contribution.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal , Hey please assign me this issue under GSSOC'23  contribution.

The design looks good, we will ask you for the changes if required. 

Please tag me if you need any assistance, I have assigned you the issue.
