### ISSUE TITLE
[OTHER] Shouldn't the `teams` page be `team`?

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#471]
### What would you like to share?

This is not a major issue at all; however, I think it would more consistent and better to name the page "team", as we're mentioning the whole WebXDAO **team**, not **teams** (even though we have multiple teams or sub-teams, I don't think that counts).

In case it's going to be updated, a redirect should be added, IMO.
What do you think about this? Thanks. 🙂

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by mkubdev** [comment]
Well spotted!

**Comment by Panquesito7** [comment]
Thanks! Working on this. 🙂
