### ISSUE TITLE
blog button in navbar  is not working 

### ISSUE THREAD

**Issue by anuza08** [WebXDAO/WebXDAO.github.io#472]
### Description of the bug

adding a link to direct to the blog section

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Gauravbisht231** [comment]
is the issue assgined to you bro? @anuza08
