### ISSUE TITLE
[FEATURE]: Footer Improvement

### ISSUE THREAD

**Issue by ShreyaDhiman24** [WebXDAO/WebXDAO.github.io#473]
### Detailed description

![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/98320971/a3dc067d-0c1d-4230-b755-f57e4785f672)

### Context

Footer can be improved further.
Wish to work under GSSoC'23. 

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by thehashmap** [comment]
Can you please share what you would like to improve?

**Comment by ShreyaDhiman24** [comment]
> Can you please share what you would like to improve?

Yeah! 
1. Centre aligning copyright and adding black background only to this part of code or adding background of any other colour of as per the site. 
2. Also, covering space in between accordingly if required.
3. Adding different hover effects to text making it look alive.

**Comment by thehashmap** [comment]
This issue appears to be similar to #470. I recommend waiting for updates on that particular issue to avoid duplicating efforts.
