### ISSUE TITLE
[FEATURE] want some css change in Contributor card

### ISSUE THREAD

**Issue by biplavmz** [WebXDAO/WebXDAO.github.io#480]
### Detailed description

Hey Look at this design 

### Context

css change

### Additional information

<img width="493" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/68702055/26b55686-0cd9-49f2-9975-548b5155e575">

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by mkubdev** [comment]
Hi! The first cards look very cool 🔥 
What do you think @WebXDAO/gssoc-mentors @WebXDAO/webx-guild-designers ?

**Comment by Anmol-Baranwal** [comment]
> Hi! The first cards look very cool 🔥 What do you think @WebXDAO/gssoc-mentors @WebXDAO/webx-guild-designers ?

So, did he made a PR?
