### ISSUE TITLE
[BUG] Images Missing 

### ISSUE THREAD

**Issue by biplavmz** [WebXDAO/WebXDAO.github.io#481]
### Description of the bug

profile images missing in Team page

### Please add screenshots (if applicable)

<img width="618" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/68702055/c89c922b-0b7e-497e-95ea-19af1f210589">

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by vinzvinci** [comment]
Thanks, but similar to #436. Closing this now!
