### ISSUE TITLE
[BUG] <bug description>

### ISSUE THREAD

**Issue by ArslanYM** [WebXDAO/WebXDAO.github.io#491]
### Description of the bug

The blogs section doesnt work.

### Please add screenshots (if applicable)

![blogs](https://github.com/WebXDAO/WebXDAO.github.io/assets/104521101/6cd708db-c26a-4d21-bf6d-0a66f51e478a)

### Add any other context about the problem here

What is the functionality of this section and how shoudl it behave?

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hello @ArslanYM, could you kindly provide clarification on the issue? If you suspect the problem lies in containers extending beyond the screen width, rest assured that the card section is intentionally designed to be scrollable.

**Comment by ArslanYM** [comment]
Yeah but its not scrolling

**Comment by s2sharpit** [comment]
> Yeah but its not scrolling

It's perfectly working in my device.

https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/ce62c2df-19a4-4037-84dd-39aa8c19a12d

**Comment by ArslanYM** [comment]
It works only after shift scroll, I think we can add a auto play feature to this. Will look better. Can I work on it?
