### ISSUE TITLE
want to add search Feature for contributors.

### ISSUE THREAD

**Issue by biplavmz** [WebXDAO/WebXDAO.github.io#494]
### Detailed description

<img width="707" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/68702055/41cc25be-6602-4424-bf30-98ff59e5626c">

### Context

contributor can easily search there profile.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Jonnie-Dev** [comment]
Hello @biplavmz, I would love to work on this

**Comment by biplavmz** [comment]
i am working on this @Jonnie-Dev

**Comment by Jonnie-Dev** [comment]
Ooh, alright.
