### ISSUE TITLE
🐛 In navbar there is no active tab and onhover and animation missing 

### ISSUE THREAD

**Issue by biplavmz** [WebXDAO/WebXDAO.github.io#495]
### Description of the bug

🐛 In navbar there is no active tab and onhover and animation missing 
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level. 

### Please add screenshots (if applicable)

<img width="421" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/68702055/c1902e17-b916-4545-aceb-11588de9d920">

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by mkubdev** [comment]
Hello :wave:
Well spotted, do you want to work on it?

**Comment by biplavmz** [comment]
yes

**Comment by biplavmz** [comment]
can you please me under gssoc23 label and level tag
