### ISSUE TITLE
[FEATURE]: Improve "Read More" Button with hovering with background-color Similar Design Like Blogs Page

### ISSUE THREAD

**Issue by NarendraKoya999** [WebXDAO/WebXDAO.github.io#496]
### Detailed description

- **Improve `"Read More" Button with hovering with background-color` Similar Design Like `Blogs Page`**
- **Because of, I strongly believe Consistency is Important for Maintain Good Website in UI and Features Wise**

### I have shared Screenshots. One is from Bolgs Page and Other one is from Projects Page
**Blogs Page Read More Button whenever Mouse Hover Action Done**

![webxdad-4](https://github.com/WebXDAO/WebXDAO.github.io/assets/84512164/2d9b99af-37ae-4eb1-ae80-f6acf2d130c0)

**Projects Page Read More Button Still No Hover Action with Background Color is not Designed**
![webxdad-3](https://github.com/WebXDAO/WebXDAO.github.io/assets/84512164/0abf2090-44d6-4b0e-b492-8d0cfbce727b)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by NarendraKoya999** [comment]
Hi @Anmol-Baranwal . Please review on my Issue as soon as Possible. If Selectable, Please assign me

**Comment by Anmol-Baranwal** [comment]
@mkubdev 
What do you think? Is this needed for the current design.

**Comment by NarendraKoya999** [comment]
> @mkubdev What do you think? Is this needed for the current design.

For Consistency Point of view, It's need for the Current Design?

**Comment by mkubdev** [comment]
> @mkubdev What do you think? Is this needed for the current design.

I honestly prefer the current version with white and no background on hover, it look more clean.
But the homepage have this gray also on the partners cards `#64748b` :
![image](https://github.com/WebXDAO/WebXDAO.github.io/assets/50140834/f521a0df-be27-4316-a00c-515049a4651b)

But as mentioned, to match blog post changes look good to me! :)

> For Consistency Point of view, It's need for the Current Design?

Yes, consistency is essential in design. It helps users understand and predict the behavior of the system, making it easier to use and learn!

**Comment by NarendraKoya999** [comment]
Any Update on this Issue @mkubdev and  @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
@NarendraKoya999 
The current design does not require any necessary changes.
