### ISSUE TITLE
[FEATURE]: Add title (Tooltip) and aria-label attribute (Web Accessibility) for Social Icons of Team Cards and Contributors Pages

### ISSUE THREAD

**Issue by NarendraKoya999** [WebXDAO/WebXDAO.github.io#497]
### Detailed description

- **Add `title (Tooltip) and aria-label attribute for Social Icons of Team Cards when Hovering Action Done`**
- **This enhancement already used in Footer Sections in Some Pages. So, I suggest to add title and aria-label attribute to Teams Card Section also.**
- **These above points are also existed in Contributors Page Also**

### Context

- **The aria-label attribute provides a way to place a descriptive text label on an object, such as a link, when there are no elements visible on the page that describe the object.**
- **The title attribute gives users an important indication as to where they will be directed to when they click on a link. If the user hovers with the mouse over a link reference, the title text, which was defined in the attribute, will be displayed.**
- **For These two above scenarios based on adding title and aria-label is must and should for Web Accessibility and Screen Readers Point of View** 

### Additional information
**Teams Card Page**

![webxdad-5](https://github.com/WebXDAO/WebXDAO.github.io/assets/84512164/160d02e3-d23d-4f16-851d-4b77ebd8aec5)

**Contributors Page**

![webxdad-6](https://github.com/WebXDAO/WebXDAO.github.io/assets/84512164/f8dd7fae-2d32-4952-87d1-8dc1836f6296)

_No response_

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by NarendraKoya999** [comment]
Hi @Anmol-Baranwal . Please review on this Issue as soon as possible. If acceptable, Please assign me

**Comment by Anmol-Baranwal** [comment]
@NarendraKoya999 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
