### ISSUE TITLE
To delete teams page which is redirecting from `/teams` to `/team`

### ISSUE THREAD

**Issue by s2sharpit** [WebXDAO/WebXDAO.github.io#501]
### What would you like to share?

To delete teams page which is redirecting from `/teams` to `/team`

<img width="480" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/4fe63df1-88c7-480d-8356-550f1902561f">

<img width="687" alt="image" src="https://github.com/WebXDAO/WebXDAO.github.io/assets/104740281/0b44f252-ab31-4bbf-adf3-f62d1219c9e6">

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by s2sharpit** [comment]
Hey @Anmol-Baranwal @vinzvinci
Kindly check this issue.

**Comment by Anmol-Baranwal** [comment]
@s2sharpit 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
