### ISSUE TITLE
[FEATURE]: Convert png, svg Images File Format into webp File Formats🌟🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [WebXDAO/WebXDAO.github.io#504]
### Purpose of Raising this Issue
- **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**

### Before Conversion

![webx-1](https://github.com/WebXDAO/WebXDAO.github.io/assets/84512164/3e994de0-2db5-4fc1-8646-ac47082e3b70)

### After Conversion

![webx-2](https://github.com/WebXDAO/WebXDAO.github.io/assets/84512164/7e87f12b-8671-47cc-ab2c-aae8a0dd871d)

### Additional information

- **I have taken One of PNG Image File in Your Project Directory.**
- **Observe above Screenshots.  Clearly Tells, Image File Size is drastically changed half of the above while Converting png to webp File Format.**
- **So, I want to work on those changes in Both Project Directory and Respective Codebase Files also.**

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by NarendraKoya999** [comment]
Hi @mkubdev . Can I go with this Issue? . For Because of You can given Like Emoji .

**Comment by mkubdev** [comment]
Hey sure I assign it yo you!

**Comment by NarendraKoya999** [comment]
Hi @mkubdev . I have one Doubt regarding My Issues. That is, In Project Directory, there is no Images Folder Placed. But, You can use same thing Couple of Files. Please Check. If my Arguments are Correct, I can edit to Right Path to the Specific Image Elements.?
