### ISSUE TITLE
[OTHER] Expand the list of codeowners

### ISSUE THREAD

**Issue by Anmol-Baranwal** [WebXDAO/WebXDAO.github.io#512]
### What would you like to share?

I will also add special cases with several other directories, so that it is easy for future changes.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by Anmol-Baranwal** [comment]
@mkubdev 
Should I make a PR?

You can look at this for reference: https://github.com/rupali-codes/LinksHub/blob/main/.github/CODEOWNERS

> The structure could be important. Let me know what you think.

**Comment by mkubdev** [comment]
@Anmol-Baranwal Sorry, just watching this issue. LGTM!

**Comment by Anmol-Baranwal** [comment]
Ah! No worries.

I will make a PR in a day or two then.

**Comment by mkubdev** [comment]
Sure np!
Also we should remove @WebXDAO/webx-guild from codeowners
