### ISSUE TITLE
[OTHER]: Want to chage Twitter logo

### ISSUE THREAD

**Issue by PatilHarshh** [WebXDAO/WebXDAO.github.io#525]
### What would you like to share?

As Twitter logo is changed it is good to change twitter logo now in our website too XD

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/WebXDAO/WebXDAO.github.io/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/WebXDAO/WebXDAO.github.io/issues)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by PatilHarshh** [comment]
@Anmol-Baranwal

**Comment by mkubdev** [comment]
OK i assign you! Do you have the new X logo ?

**Comment by SudeeptaGiri** [comment]
I want to work on this Issue
