### ISSUE TITLE
[FEATURE] Add a page for our community moderators

### ISSUE THREAD

**Issue by Panquesito7** [WebXDAO/WebXDAO.github.io#91]
### Detailed description

Add a page for all of our community moderators. They should be credited for their work in keeping the community a safe and welcoming environment for all. Also, for their continuous help. 😉

### Context

Other communities have a moderators page as well. Also, I think it would benefit the moderators to promote themselves a bit. 🙂

### Possible implementation

We could make it a simple page with their profile photos and links to their GitHub profile or any other socials they want, and a short bio of themselves. 🙂

### Additional information

I don't think so.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shreyaansjain06** [comment]
I can do this please assign this issue to me

**Comment by shreyaansjain06** [comment]
Sorry for the delay i was a busy earlier
Can you share some content like moderator details so i can make it

**Comment by shuklaritvik06** [comment]
> > You should find a way to fetch the GitHub api to list contributors from the organization.
> > Hint : https://docs.github.com/en/rest/reference/repos#list-contributors
> 
> I think this issue is about moderators not contributors slightly_smiling_face

Yep for active contributors we have another issue #45

**Comment by mkubdev** [comment]
> > You should find a way to fetch the GitHub api to list contributors from the organization.
> > Hint : https://docs.github.com/en/rest/reference/repos#list-contributors
> 
> I think this issue is about moderators not contributors 🙂

Woops, my bad. 😇 Don't know yet if we can list moderators only.

**Comment by krishguptadev** [comment]
> > > > You should find a way to fetch the GitHub api to list contributors from the organization.
> > > > Hint : https://docs.github.com/en/rest/reference/repos#list-contributors
> > > 
> > > 
> > > I think this issue is about moderators not contributors 🙂
> > 
> > 
> > Woops, my bad. 😇 Don't know yet if we can list moderators only.
> 
> Yeah, that isn't that hard. We can add them manually.

So @vinzvinci Can you collect and share the details?

**Comment by vinzvinci** [comment]
Moderators: @Panquesito7 @shuklaritvik06 @KukretiShubham @vinzvinci
