### ISSUE TITLE
[FEATURE] Update Community Partners subtitle

### ISSUE THREAD

**Issue by mkubdev** [WebXDAO/WebXDAO.github.io#96]
### Detailed description

Remove latin and add a subtitle to the community partners page.

### Context

Latin is for mocked view, we need subtitle implementation.

### Possible implementation

Speak about it here! 📢

### Additional information

![Capture](https://user-images.githubusercontent.com/50140834/136801565-125ddf10-1169-48ca-a677-24a2d4e4b4d1.JPG)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohitbalwani** [comment]
Thanks for helping! I have created a PR to close this issue.
